In [1]:
library(tidyverse)
library(data.table)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.6
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()


Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose

In [ ]:
# from http://resource.psychencode.org/

In [2]:
loops <- fread("INT-16_HiC_EP_linkages_cross_assembly.csv")

In [3]:
head(loops)

  Enhancer_Chromosome_hg19 Enhancer_Start_hg19 Enhancer_End_hg19
1 chr1                     10009834            10010384
2 chr1                     10009834            10010384
3 chr1                     10009834            10010384
4 chr1                     10010405            10010953
5 chr1                     10010405            10010953
6 chr1                     10010405            10010953
  PEC_Enhancer_ID Enhancer_Chromosome_hg38 Enhancer_Start_hg38
1 EH37E0068723    chr1                     9949776
2 EH37E0068723    chr1                     9949776
3 EH37E0068723    chr1                     9949776
4 EH37E0068724    chr1                     9950347
5 EH37E0068724    chr1                     9950347
6 EH37E0068724    chr1                     9950347
  Enhancer_End_hg38 Transcription_Start_Site_hg19 Target_Gene_Name
1 9950326           10480000                      CENPS-CORT
2 9950326           10480000                      CENPS
3 9950326           10290000                      KIF1B
4 9950895           10480000                      CENPS-CORT
5 9950895           10290000                      KIF1B
6 9950895           10480000                      CENPS
  Target_Ensembl_Name
1 ENSG00000251503
2 ENSG00000175279
3 ENSG00000054523
4 ENSG00000251503
5 ENSG00000054523
6 ENSG00000175279

In [4]:
gene_pos <- read.csv("../20241126_eqtl_based_scores/asd_gene_pos.csv")
gene_pos <- gene_pos[,-1]

In [5]:
head(gene_pos)

  hgnc_symbol start_position end_position chromosome_name
1 ACTL6B      100643097      100656448    7
2 ADNP         50888916       50931437    20
3 ALDH1A3     100861924      100916626    15
4 ALDH1A3-AS1 100892343      100920312    15
5 AMPD1       114673090      114695618    1
6 ANK2        112818032      113384221    4

In [6]:
scores <- fread("/u/home/a/aflynnca/project-pasaniuc/projects/20241015_asd_pgs/20241024_asd_pgs/PGS000327_hmPOS_GRCh38.txt")

In [6]:
head(scores)

  rsID        chr_name chr_position effect_allele other_allele effect_weight
1 rs113901932 8        100228085    A             G            -0.0598031
2 rs151150581 8        100422898    T             C             0.0483043
3 rs76228276  8        100638095    A             C            -0.0610991
4 rs13260744  8        100831260    A             G            -0.0456984
5 rs7832556   8        100923156    A             G             0.0259016
6 rs7830618   8        100926037    T             C            -0.0382004
  variant_description hm_source hm_rsID     hm_chr hm_pos   hm_inferOtherAllele
1                     ENSEMBL   rs113901932 8      99215857 NA
2                     ENSEMBL   rs151150581 8      99410670 NA
3                     ENSEMBL   rs76228276  8      99625867 NA
4                     ENSEMBL   rs13260744  8      99819032 NA
5                     ENSEMBL   rs7832556   8      99910928 NA
6                     ENSEMBL   rs7830618   8      99913809 NA

In [3]:
head(loops)

  V1
1 # this file is in format of chromosome, TSS_start, TSS_end, Interacting_region_start, Interacting_region_end; TSS and Interacting regions are in 10kb size (due to the resolution of Hi-C)
2 10
3 10
4 10
5 10
6 10
  V2        V3        V4        V5
1        NA        NA        NA        NA
2 100080000 100090000 100920000 100930000
3 100080000 100090000 101020000 101030000
4 100180000 100190000  99530000  99540000
5 100180000 100190000 100960000 100970000
6 100180000 100190000 100990000 101000000

In [5]:
#colnames(loops) <- c("chrom", "TSS_start", "TSS_end", "Interacting_region_start", "Interacting_region_end")

In [7]:
loop_sub <- loops[loops$Target_Gene_Name %in% gene_pos$hgnc_symbol,]

In [8]:
dim(loop_sub)

[1] 518  10

In [13]:
head(loop_sub)

  Enhancer_Chromosome_hg19 Enhancer_Start_hg19 Enhancer_End_hg19
1 chr1                     209761108           209761575
2 chr1                     209762843           209763265
3 chr1                     209763323           209763533
4 chr1                     209763689           209764079
5 chr1                      61545048            61545298
6 chr1                      61551388            61551849
  PEC_Enhancer_ID Enhancer_Chromosome_hg38 Enhancer_Start_hg38
1 EH37E0137552    chr1                     209587763
2 EH37E0137553    chr1                     209589498
3 EH37E0137554    chr1                     209589978
4 EH37E0137555    chr1                     209590344
5 EH37E0092971    chr1                      61079376
6 EH37E0092972    chr1                      61085716
  Enhancer_End_hg38 Transcription_Start_Site_hg19 Target_Gene_Name
1 209588230         209790000                     LAMB3
2 209589920         209790000                     LAMB3
3 209590188         209790000                     LAMB3
4 209590734         209790000                     LAMB3
5  61079626          61510000                     NFIA
6  61086177          61510000                     NFIA
  Target_Ensembl_Name
1 ENSG00000196878
2 ENSG00000196878
3 ENSG00000196878
4 ENSG00000196878
5 ENSG00000162599
6 ENSG00000162599

In [21]:
unique(loop_sub$Enhancer_Chromosome_hg38)

 [1] "chr1"  "chr10" "chr11" "chr14" "chr15" "chr16" "chr17" "chr18" "chr19"
[10] "chr2"  "chr20" "chr22" "chr3"  "chr4"  "chr5"  "chr7"  "chr8"  "chr9"
[19] "chrX"

In [ ]:
loop_sub$Enhancer_Chromosome_hg38[loop_sub$Enhancer_Chromosome_hg38]

In [27]:
loop_sub$chrom_38 <- gsub("chr", "", loop_sub$Enhancer_Chromosome_hg38)

In [25]:
unique(loop_sub$chrom)

 [1] "1"  "10" "11" "14" "15" "16" "17" "18" "19" "2"  "20" "22" "3"  "4"  "5"
[16] "7"  "8"  "9"  NA

In [23]:
unique(scores$hm_chr)

 [1] "8"                 "2"                 "16"
 [4] "7"                 "6"                 "15"
 [7] "14"                "12"                "17"
[10] "1"                 "3"                 "11"
[13] "22"                "20"                "21"
[16] "9"                 "4"                 "13"
[19] "5"                 "10"                "18"
[22] ""                  "19"                "19_KI270938v1_alt"
[25] "7_KI270803v1_alt"

In [14]:
head(scores)

  rsID        chr_name chr_position effect_allele other_allele effect_weight
1 rs113901932 8        100228085    A             G            -0.0598031
2 rs151150581 8        100422898    T             C             0.0483043
3 rs76228276  8        100638095    A             C            -0.0610991
4 rs13260744  8        100831260    A             G            -0.0456984
5 rs7832556   8        100923156    A             G             0.0259016
6 rs7830618   8        100926037    T             C            -0.0382004
  variant_description hm_source hm_rsID     hm_chr hm_pos   hm_inferOtherAllele
1                     ENSEMBL   rs113901932 8      99215857 NA
2                     ENSEMBL   rs151150581 8      99410670 NA
3                     ENSEMBL   rs76228276  8      99625867 NA
4                     ENSEMBL   rs13260744  8      99819032 NA
5                     ENSEMBL   rs7832556   8      99910928 NA
6                     ENSEMBL   rs7830618   8      99913809 NA

In [14]:
subset_by_ranges <- function(scores, var_ranges, pos_col, start_col, end_col, chr_filt, chr_score) {
  # Check if positions in scores are within any of the ranges in var_ranges and chromosomes match
  in_range <- sapply(
    1:nrow(scores),  # Loop through each row in scores
    function(i) {
      # Find matching chromosomes in var_ranges for each position
      chr_match <- var_ranges[[chr_filt]] == scores[[chr_score]][i]
      # Check if the position falls within the range for matching chromosomes
      any(chr_match & scores[[pos_col]][i] >= var_ranges[[start_col]] & scores[[pos_col]][i] <= var_ranges[[end_col]])
    }
  )
  
  # Subset and return the filtered scores
  return(scores[in_range, ])
}

In [15]:
# Call the function with chromosome matching
gene_score_sub <- subset_by_ranges(
  scores = scores,
  var_ranges = loop_sub,
  pos_col = "hm_pos",     # Column in scores with positions
  start_col = "Enhancer_Start_hg38",    # Start column in var_ranges
  end_col = "Enhancer_End_hg38",       # End column in var_ranges
  chr_filt = "Enhancer_Chromosome_hg38",
  chr_score = "hm_chr"
)

In [16]:
dim(gene_score_sub)

[1]  0 12

In [40]:
# Filter scores based on the conditions
filtered_scores <- scores %>%
  rowwise() %>%
  filter(any(
    hm_chr == loop_sub$chrom_38 &
    hm_pos >= loop_sub$Enhancer_Start_hg38 &
    hm_pos <= loop_sub$Enhancer_End_hg38
  )) %>%
  ungroup()

In [30]:
dim(scores)

[1] 35087    12

In [39]:
filtered_scores

  rsID chr_name chr_position effect_allele other_allele effect_weight
1      18       56456233     T             C            0.0477039
  variant_description hm_source hm_rsID hm_chr hm_pos   hm_inferOtherAllele
1                     liftover          18     58789001 NA

In [31]:
# Filter scores based on the conditions
filtered_scores <- scores %>%
  rowwise() %>%
  filter(any(
    hm_chr == loop_sub$Enhancer_Chromosome_hg38 &
    hm_pos >= loop_sub$Enhancer_Start_hg38 &
    hm_pos <= loop_sub$chrom_38
  )) %>%
  ungroup()

In [34]:
# Call the function with chromosome matching
gene_score_sub <- subset_by_ranges_og(
  scores = scores,
  var_ranges = gene_pos,
  pos_col = "hm_pos",     # Column in scores with positions
  start_col = "start_position",    # Start column in var_ranges
  end_col = "end_position",       # End column in var_ranges
  chr_col = "chr_name"          # Column in both scores and var_ranges for chromosomes
)

In [37]:
head(gene_pos)

  hgnc_symbol start_position end_position chromosome_name
1 ACTL6B      100643097      100656448    7
2 ADNP         50888916       50931437    20
3 ALDH1A3     100861924      100916626    15
4 ALDH1A3-AS1 100892343      100920312    15
5 AMPD1       114673090      114695618    1
6 ANK2        112818032      113384221    4