In [1]:
library(data.table)

In [13]:
related_df <- as.data.frame(fread("bash_filtered_grm.txt"))

In [49]:
ids <- as.data.frame(fread("spark_hm3_joined.grm.id", header=F))

In [29]:
typeof(related_df$V4)

[1] "double"

In [15]:
head(related_df)

  V1 V2 V3     V4
1 1  1  636516 0.9818537
2 2  2  636516 1.0124830
3 3  3  636516 1.0035510
4 4  3  636516 0.5055295
5 4  4  636516 1.0021130
6 5  3  636516 0.5088581

In [4]:
dim(related_df)

[1] 21219337        4

In [50]:
head(ids)

  V1        V2
1 SF0000003 SP0000003
2 SF0000017 SP0000017
3 SF0000027 SP0000027
4 SF0000027 SP0000034
5 SF0000027 SP0000051
6 SF0000027 SP0000063

In [45]:
ids[1,]

  SF0000003 SP0000003
1 SF0000017 SP0000017

In [17]:
related_df <- subset(related_df, related_df[,1] != related_df[,2])

In [18]:
head(related_df)

   V1 V2 V3     V4
4  4  3  636516 0.5055295
6  5  3  636516 0.5088581
7  5  4  636516 0.5039278
9  6  3  636516 0.4755138
10 6  4  636516 0.5472862
11 6  5  636516 0.5003096

In [58]:
dim(related_df)

[1] 21149850        5

In [55]:
related_df$V1 <- ids[related_df$V1,]$V2

In [56]:
related_df$V2 <- ids[related_df$V2,]$V2

In [60]:
head(related_df)

   id1       id2       var_used relatedness test
4  SP0000034 SP0000027 636516   0.5055295   SP0000034
6  SP0000051 SP0000027 636516   0.5088581   SP0000051
7  SP0000051 SP0000034 636516   0.5039278   SP0000051
9  SP0000063 SP0000027 636516   0.4755138   SP0000063
10 SP0000063 SP0000034 636516   0.5472862   SP0000063
11 SP0000063 SP0000051 636516   0.5003096   SP0000063

In [59]:
colnames(related_df) <- c("id1", "id2", "var_used", "relatedness", "test")

In [61]:
write.csv(related_df[,1:4], file = "related_individuals.txt", row.names = FALSE)

In [21]:
related_df[related_df$V1 == 4 | related_df$V2 == 4,]

   V1 V2 V3     V4
4  4  3  636516 0.5055295
7  5  4  636516 0.5039278
10 6  4  636516 0.5472862
14 7  4  636516 0.5005428

In [24]:
related_df[related_df$V1 == 5 | related_df$V2 == 5,]

   V1 V2 V3     V4
6  5  3  636516 0.5088581
7  5  4  636516 0.5039278
11 6  5  636516 0.5003096

In [25]:
range(related_df$V4)

[1] 0.05000001 1.09931700

In [30]:
related_df[related_df$V4 >= 1,]

         V1    V2    V3     V4
68          38    37 636516 1.003864
1136       478   476 636516 1.006971
6017      1702  1701 636516 1.009652
9346      2351  2350 636516 1.001354
11320     2616  2615 636516 1.013880
16728     3389  3388 636516 1.003798
18275     3562  3561 636516 1.007855
18916     3605  3604 636516 1.017436
20348     3722  3721 636516 1.087868
22153     3931  3930 636516 1.006595
27012     4241  4240 636516 1.015205
28549     4373  4372 636516 1.000315
32639     4602  4601 636516 1.011183
32666     4618  4617 636516 1.006824
33726     4644  4643 636516 1.043865
95067     6870  6868 636516 1.001296
113630    7292  7291 636516 1.049879
133618    7896  7895 636516 1.010925
141883    8138  8137 636516 1.004884
171127    8568  8567 636516 1.000717
184619    8981  8980 636516 1.008873
214979    9401  9400 636516 1.001769
345872   11231 11230 636516 1.012704
456103   12200 12199 636516 1.099317
677424   14296 14295 636516 1.000474
765883   15239 15237 636516 1.003515
792152   15527 15526 636516 1.001023
808407   15748 15747 636516 1.009078
840129   16070 16069 636516 1.089584
909836   16869 16868 636516 1.004036
⋮        ⋮     ⋮     ⋮      ⋮
5624225  39639 39638 636516 1.009634
5653025  39793 39792 636516 1.008300
6086829  40954 40953 636516 1.008661
6697340  42868 42867 636516 1.007676
6820348  43282 43281 636516 1.005691
6864043  43345 43344 636516 1.008419
6864108  43346 43344 636516 1.009132
6864109  43346 43345 636516 1.008422
7031297  43813 43812 636516 1.013648
7078733  43945 43944 636516 1.090450
7105132  44078 44077 636516 1.000442
7296550  44774 44773 636516 1.029539
7322300  44874 44873 636516 1.002550
7437059  45245 45244 636516 1.005180
8126862  47149 47148 636516 1.080151
8464919  47902 47901 636516 1.005237
8488094  48035 48034 636516 1.006416
8505456  48088 48087 636516 1.000064
8851002  48906 48905 636516 1.007681
9235202  49636 49635 636516 1.009917
9378748  49985 49984 636516 1.010153
9420674  50096 50095 636516 1.005602
9477571  50183 50182 636516 1.000980
9532744  50280 50279 636516 1.000460
9994794  51307 51306 636516 1.010438
11269046 54023 54022 636516 1.003034
12093257 55545 55544 636516 1.002873
12638855 56543 56542 636516 1.001543
16044824 62147 62146 636516 1.005002
16090771 62204 62203 636516 1.017023