In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.6
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
library(data.table)

Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose

In [4]:
score <- fread("PGS000327_hmPOS_GRCh38.txt")

In [5]:
head(score)

  rsID        chr_name chr_position effect_allele other_allele effect_weight
1 rs113901932 8        100228085    A             G            -0.0598031
2 rs151150581 8        100422898    T             C             0.0483043
3 rs76228276  8        100638095    A             C            -0.0610991
4 rs13260744  8        100831260    A             G            -0.0456984
5 rs7832556   8        100923156    A             G             0.0259016
6 rs7830618   8        100926037    T             C            -0.0382004
  variant_description hm_source hm_rsID     hm_chr hm_pos   hm_inferOtherAllele
1                     ENSEMBL   rs113901932 8      99215857 NA
2                     ENSEMBL   rs151150581 8      99410670 NA
3                     ENSEMBL   rs76228276  8      99625867 NA
4                     ENSEMBL   rs13260744  8      99819032 NA
5                     ENSEMBL   rs7832556   8      99910928 NA
6                     ENSEMBL   rs7830618   8      99913809 NA

In [6]:
score <- score[, c("hm_chr", "hm_pos", "effect_allele", "other_allele", "effect_weight")]

In [7]:
head(score)

  hm_chr hm_pos   effect_allele other_allele effect_weight
1 8      99215857 A             G            -0.0598031
2 8      99410670 T             C             0.0483043
3 8      99625867 A             C            -0.0610991
4 8      99819032 A             G            -0.0456984
5 8      99910928 A             G             0.0259016
6 8      99913809 T             C            -0.0382004

In [8]:
colnames(score) <- c("chr_name", "chr_position", "effect_allele", "other_allele", "effect_weight")

In [10]:
fwrite(score, file = "asd_hg38_grove.txt", sep = "\t")

In [ ]:
# #genome_build=GRCh38
# added to top of file after creation