In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [30]:
ace_ibd <- read.table("ace_ibd.genome")

In [16]:
sa_covar <- read.csv("ace_spark_total_covar.csv")

In [17]:
head(sa_covar)

  X sampleset sp_id                         FID         IID            ASD
1 1 ace       702-A-80310.01_702-A-80310.01 702-A-80310 702-A-80310.01 NA
2 2 ace       702-A-80310.02_702-A-80310.02 702-A-80310 702-A-80310.02 NA
3 3 ace       702-A-80310.03_702-A-80310.03 702-A-80310 702-A-80310.03 NA
4 4 ace       702-A-80310.04_702-A-80310.04 702-A-80310 702-A-80310.04 NA
5 5 ace       702-A-80310.05_702-A-80310.05 702-A-80310 702-A-80310.05 NA
6 6 ace       702-A-80330.01_702-A-80330.01 702-A-80330 702-A-80330.01 NA
  total_PGS Age Sex ancestry ⋯ PC3       PC4      PC5       PC6
1 -39.8345  NA  1   AMR      ⋯ -74.07577 63.78452  9.054176 -2.2269743
2 -51.1747  NA  2   AMR      ⋯ -53.23033 11.79616 -1.202906  0.6570949
3 -43.9219  NA  1   AMR      ⋯ -65.51733 41.20630  3.837885 -0.8561451
4 -47.4659  NA  1   AMR      ⋯ -63.47658 35.34593  6.460086 -0.2317628
5 -43.9489  NA  2   AMR      ⋯ -71.61951 46.30474  3.092592 -1.9796365
6 -43.6181  NA  1   AMR      ⋯ -97.16606 76.97857  2.219987 -0.5894056
  PC7        PC8        PC9         PC10       scaled_score sample_q
1  2.9067341 -3.3447619  3.53786288  -1.203545  0.5531031   1
2 -1.8168367  0.7443870 -4.35465079 -11.322266 -1.8142342   1
3 -0.6773332 -0.4422768 -0.36567141  -5.315208 -0.3001671   1
4  2.6333871  0.2320523  0.85765385  -8.841262 -1.0399992   1
5  0.4718819 -0.6072317 -0.41069401  -6.168888 -0.3058035   1
6 -0.2014303 -3.4020371 -0.01629822   2.687088 -0.2367470   1

In [18]:
table(sa_covar$sampleset)

  ace SPARK
 2612 68316

In [21]:
sa_covar <- sa_covar[sa_covar$sampleset == "ace", c("FID", "IID")]

In [4]:
head(ace_ibd)

  V1   V2                            V3   V4                            V5 V6
1 FID1 IID1                          FID2 IID2                          RT EZ
2 0    702-A-80310.01_702-A-80310.01 0    702-A-80310.02_702-A-80310.02 OT 0
3 0    702-A-80310.01_702-A-80310.01 0    702-A-80310.03_702-A-80310.03 OT 0
4 0    702-A-80310.01_702-A-80310.01 0    702-A-80310.04_702-A-80310.04 OT 0
5 0    702-A-80310.01_702-A-80310.01 0    702-A-80310.05_702-A-80310.05 OT 0
6 0    702-A-80310.01_702-A-80310.01 0    702-A-80330.01_702-A-80330.01 OT 0
  V7     V8     V9     V10    V11 V12      V13    V14
1 Z0     Z1     Z2     PI_HAT PHE DST      PPC    RATIO
2 0.9192 0.0617 0.0192 0.0500 -1  0.643202 0.7195 2.0420
3 0.0021 0.9440 0.0539 0.5259 -1  0.766361 1.0000 994.0000
4 0.0028 0.9606 0.0366 0.5169 -1  0.762006 1.0000 598.4000
5 0.0023 0.9390 0.0587 0.5282 -1  0.767524 1.0000 500.0000
6 0.8715 0.1205 0.0080 0.0683 -1  0.646421 0.9059 2.0975

In [31]:
colnames(ace_ibd) <- as.character(unlist(ace_ibd[1, ]))
ace_ibd <- ace_ibd[-1, ]

In [32]:
ace_ibd$IID1 <- sub(".*_", "", ace_ibd$IID1)

In [33]:
ace_ibd$IID2 <- sub(".*_", "", ace_ibd$IID2)

In [34]:
head(ace_ibd)

  FID1 IID1           FID2 IID2           RT EZ Z0     Z1     Z2     PI_HAT PHE
2 0    702-A-80310.01 0    702-A-80310.02 OT 0  0.9192 0.0617 0.0192 0.0500 -1
3 0    702-A-80310.01 0    702-A-80310.03 OT 0  0.0021 0.9440 0.0539 0.5259 -1
4 0    702-A-80310.01 0    702-A-80310.04 OT 0  0.0028 0.9606 0.0366 0.5169 -1
5 0    702-A-80310.01 0    702-A-80310.05 OT 0  0.0023 0.9390 0.0587 0.5282 -1
6 0    702-A-80310.01 0    702-A-80330.01 OT 0  0.8715 0.1205 0.0080 0.0683 -1
7 0    702-A-80310.01 0    702-A-80330.02 OT 0  0.8953 0.1007 0.0039 0.0543 -1
  DST      PPC    RATIO
2 0.643202 0.7195 2.0420
3 0.766361 1.0000 994.0000
4 0.762006 1.0000 598.4000
5 0.767524 1.0000 500.0000
6 0.646421 0.9059 2.0975
7 0.642429 0.5572 2.0104

In [7]:
range(ace_ibd$PI_HAT)

[1] "0.0000" "0.9999"

In [8]:
dim(ace_ibd)

[1] 3409966      14

In [11]:
dim(ace_ibd[ace_ibd$PI_HAT >0.05,])

[1] 879944     14

In [61]:
ave_rel <- ace_ibd[ace_ibd$PI_HAT >0.05,]

In [38]:
length(unique(ave_rel$IID1))

[1] 2595

In [39]:
sum(ave_rel$IID1 %in% sa_covar$IID)

[1] 879362

In [62]:
ave_rel <- ave_rel[ave_rel$IID1 %in% sa_covar$IID & ave_rel$IID2 %in% sa_covar$IID,]

In [56]:
dim(ave_rel)

[1] 876461     16

In [50]:
head(ave_rel)

  FID1 IID1           FID2 IID2           RT EZ Z0     Z1     Z2     PI_HAT PHE
2 0    702-A-80310.01 0    702-A-80310.02 OT 0  0.9192 0.0617 0.0192 0.0500 -1
3 0    702-A-80310.01 0    702-A-80310.03 OT 0  0.0021 0.9440 0.0539 0.5259 -1
4 0    702-A-80310.01 0    702-A-80310.04 OT 0  0.0028 0.9606 0.0366 0.5169 -1
5 0    702-A-80310.01 0    702-A-80310.05 OT 0  0.0023 0.9390 0.0587 0.5282 -1
6 0    702-A-80310.01 0    702-A-80330.01 OT 0  0.8715 0.1205 0.0080 0.0683 -1
7 0    702-A-80310.01 0    702-A-80330.02 OT 0  0.8953 0.1007 0.0039 0.0543 -1
  DST      PPC    RATIO
2 0.643202 0.7195 2.0420
3 0.766361 1.0000 994.0000
4 0.762006 1.0000 598.4000
5 0.767524 1.0000 500.0000
6 0.646421 0.9059 2.0975
7 0.642429 0.5572 2.0104

In [63]:
colnames(ave_rel)

 [1] "FID1"   "IID1"   "FID2"   "IID2"   "RT"     "EZ"     "Z0"     "Z1"
 [9] "Z2"     "PI_HAT" "PHE"    "DST"    "PPC"    "RATIO"

In [64]:
ave_rel <- ave_rel[,c("IID1", "IID2", "RT", "EZ", "Z0", "Z1", "Z2", "PI_HAT", "PHE", "DST", "PPC", "RATIO")]

In [45]:
head(sa_covar)

  FID         IID
1 702-A-80310 702-A-80310.01
2 702-A-80310 702-A-80310.02
3 702-A-80310 702-A-80310.03
4 702-A-80310 702-A-80310.04
5 702-A-80310 702-A-80310.05
6 702-A-80330 702-A-80330.01

In [48]:
sa_covar$IID1 <- sa_covar$IID
sa_covar$IID2 <- sa_covar$IID
sa_covar$FID1 <-sa_covar$FID
sa_covar$FID2 <-sa_covar$FID

In [65]:
head(sa_covar)

  FID         IID            IID1           IID2           FID1
1 702-A-80310 702-A-80310.01 702-A-80310.01 702-A-80310.01 702-A-80310
2 702-A-80310 702-A-80310.02 702-A-80310.02 702-A-80310.02 702-A-80310
3 702-A-80310 702-A-80310.03 702-A-80310.03 702-A-80310.03 702-A-80310
4 702-A-80310 702-A-80310.04 702-A-80310.04 702-A-80310.04 702-A-80310
5 702-A-80310 702-A-80310.05 702-A-80310.05 702-A-80310.05 702-A-80310
6 702-A-80330 702-A-80330.01 702-A-80330.01 702-A-80330.01 702-A-80330
  FID2
1 702-A-80310
2 702-A-80310
3 702-A-80310
4 702-A-80310
5 702-A-80310
6 702-A-80330

In [66]:
ave_rel <- left_join(ave_rel, sa_covar[,c("IID1", "FID1")], by= "IID1")

In [67]:
ave_rel <- left_join(ave_rel, sa_covar[,c("IID2", "FID2")], by= "IID2")

In [54]:
head(sa_covar[,c("IID2", "FID2")])

  IID2           FID2
1 702-A-80310.01 702-A-80310
2 702-A-80310.02 702-A-80310
3 702-A-80310.03 702-A-80310
4 702-A-80310.04 702-A-80310
5 702-A-80310.05 702-A-80310
6 702-A-80330.01 702-A-80330

In [68]:
head(ave_rel)

  IID1           IID2           RT EZ Z0     Z1     Z2     PI_HAT PHE DST
1 702-A-80310.01 702-A-80310.02 OT 0  0.9192 0.0617 0.0192 0.0500 -1  0.643202
2 702-A-80310.01 702-A-80310.03 OT 0  0.0021 0.9440 0.0539 0.5259 -1  0.766361
3 702-A-80310.01 702-A-80310.04 OT 0  0.0028 0.9606 0.0366 0.5169 -1  0.762006
4 702-A-80310.01 702-A-80310.05 OT 0  0.0023 0.9390 0.0587 0.5282 -1  0.767524
5 702-A-80310.01 702-A-80330.01 OT 0  0.8715 0.1205 0.0080 0.0683 -1  0.646421
6 702-A-80310.01 702-A-80330.02 OT 0  0.8953 0.1007 0.0039 0.0543 -1  0.642429
  PPC    RATIO    FID1        FID2
1 0.7195 2.0420   702-A-80310 702-A-80310
2 1.0000 994.0000 702-A-80310 702-A-80310
3 1.0000 598.4000 702-A-80310 702-A-80310
4 1.0000 500.0000 702-A-80310 702-A-80310
5 0.9059 2.0975   702-A-80310 702-A-80330
6 0.5572 2.0104   702-A-80310 702-A-80330

In [69]:
ave_rel <- ave_rel[ave_rel$FID1 != ave_rel$FID2, ]

In [70]:
dim(ave_rel)

[1] 873627     14

In [76]:
head(ave_rel)

   IID1           IID2           RT EZ Z0     Z1     Z2     PI_HAT PHE DST
5  702-A-80310.01 702-A-80330.01 OT 0  0.8715 0.1205 0.0080 0.0683 -1  0.646421
6  702-A-80310.01 702-A-80330.02 OT 0  0.8953 0.1007 0.0039 0.0543 -1  0.642429
7  702-A-80310.01 702-A-80330.03 OT 0  0.8783 0.1104 0.0113 0.0665 -1  0.646357
8  702-A-80310.01 702-A-80330.04 OT 0  0.8966 0.1019 0.0015 0.0525 -1  0.641681
9  702-A-80310.01 702-A-80330.05 OT 0  0.8983 0.0987 0.0030 0.0524 -1  0.641831
10 702-A-80310.01 702-A-80369.01 OT 0  0.8757 0.1176 0.0067 0.0655 -1  0.645567
   PPC    RATIO  FID1        FID2
5  0.9059 2.0975 702-A-80310 702-A-80330
6  0.5572 2.0104 702-A-80310 702-A-80330
7  0.1872 1.9373 702-A-80310 702-A-80330
8  0.1593 1.9298 702-A-80310 702-A-80330
9  0.1021 1.9114 702-A-80310 702-A-80330
10 0.4242 1.9863 702-A-80310 702-A-80369

In [78]:
range(ave_rel$PI_HAT, na.rm =T)

[1] "0.0500" "0.9999"

In [79]:
ave_rel_3rd <- ave_rel[ave_rel$PI_HAT > 0.125,]

In [80]:
dim(ave_rel_3rd)

[1] 3775   14

In [81]:
head(ave_rel_3rd)

     IID1           IID2           RT EZ Z0     Z1     Z2     PI_HAT PHE
4180 702-A-80341.02 702-A-80439.03 OT 0  0.7583 0.1800 0.0617 0.1517 -1
4181 702-A-80341.02 702-B-80307.03 OT 0  0.7743 0.1361 0.0896 0.1577 -1
4182 702-A-80341.02 702-B-80312.02 OT 0  0.7655 0.1600 0.0745 0.1545 -1
4183 702-A-80341.02 702-B-80339.01 OT 0  0.7788 0.1614 0.0598 0.1405 -1
4185 702-A-80341.02 702-B-80340.03 OT 0  0.7571 0.1555 0.0874 0.1651 -1
4187 702-A-80341.02 702-M-80296.03 OT 0  0.7274 0.2008 0.0717 0.1721 -1
     DST      PPC    RATIO  FID1        FID2
4180 0.673800 0.5874 2.0163 702-A-80341 702-A-80439
4181 0.678690 0.0006 1.7788 702-A-80341 702-B-80307
4182 0.676042 0.0006 1.7779 702-A-80341 702-B-80312
4183 0.670748 0.2314 1.9470 702-A-80341 702-B-80339
4185 0.680280 0.2690 1.9552 702-A-80341 702-B-80340
4187 0.680120 0.0907 1.9039 702-A-80341 702-M-80296

In [82]:
range(ave_rel_3rd$Z1)

[1] "0.0002" "1.0000"