In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [22]:
getwd()

[1] "/u/project/pasaniuc/afcarrol/Projects/20240521_ace_ibd"

In [2]:
king_ace <- read.table("king_ace_related.kin")

In [3]:
head(king_ace)

  V1  V2              V3              V4    V5    V6     V7     V8     V9
1 FID ID1             ID2             N_SNP Z0    Phi    HetHet IBS0   HetConc
2 0   AN00090_AN00090 AN00493_AN00493 46850 1.000 0.0000 0.2185 0.1065 0.3068
3 0   AN00090_AN00090 AN00544_AN00544 46803 1.000 0.0000 0.2199 0.1074 0.3080
4 0   AN00090_AN00090 AN00764_AN00764 46850 1.000 0.0000 0.2195 0.1098 0.3076
5 0   AN00090_AN00090 AN01125_AN01125 46803 1.000 0.0000 0.2166 0.1094 0.3034
6 0   AN00090_AN00090 AN01410_AN01410 46803 1.000 0.0000 0.2195 0.1125 0.3088
  V10     V11     V12     V13     V14     V15     V16
1 HomIBS0 Kinship IBD1Seg IBD2Seg PropIBD InfType Error
2 -0.9506 0.0059  0.0083  0.0000  0.0042  UN      0
3 -0.9541 0.0055  0.0038  0.0000  0.0019  UN      0
4 -0.9998 0.0000  0.0108  0.0000  0.0054  UN      0
5 -1.0201 -0.0023 0.0152  0.0000  0.0076  UN      0
6 -1.0505 -0.0058 0.0000  0.0000  0.0000  UN      0

In [4]:
colnames(king_ace) <- as.character(unlist(king_ace[1, ]))
king_ace <- king_ace[-1, ]

In [17]:
king_ace$ID1 <- sub(".*_", "", king_ace$ID1)
king_ace$ID2 <- sub(".*_", "", king_ace$ID2)

In [5]:
head(king_ace)

  FID ID1             ID2             N_SNP Z0    Phi    HetHet IBS0   HetConc
2 0   AN00090_AN00090 AN00493_AN00493 46850 1.000 0.0000 0.2185 0.1065 0.3068
3 0   AN00090_AN00090 AN00544_AN00544 46803 1.000 0.0000 0.2199 0.1074 0.3080
4 0   AN00090_AN00090 AN00764_AN00764 46850 1.000 0.0000 0.2195 0.1098 0.3076
5 0   AN00090_AN00090 AN01125_AN01125 46803 1.000 0.0000 0.2166 0.1094 0.3034
6 0   AN00090_AN00090 AN01410_AN01410 46803 1.000 0.0000 0.2195 0.1125 0.3088
7 0   AN00090_AN00090 AN01971_AN01971 46803 1.000 0.0000 0.2196 0.1080 0.3081
  HomIBS0 Kinship IBD1Seg IBD2Seg PropIBD InfType Error
2 -0.9506 0.0059  0.0083  0.0000  0.0042  UN      0
3 -0.9541 0.0055  0.0038  0.0000  0.0019  UN      0
4 -0.9998 0.0000  0.0108  0.0000  0.0054  UN      0
5 -1.0201 -0.0023 0.0152  0.0000  0.0076  UN      0
6 -1.0505 -0.0058 0.0000  0.0000  0.0000  UN      0
7 -0.9673 0.0039  0.0053  0.0000  0.0027  UN      0

In [6]:
king_ace <- king_ace[,-1]

In [7]:
head(king_ace)

  ID1             ID2             N_SNP Z0    Phi    HetHet IBS0   HetConc
2 AN00090_AN00090 AN00493_AN00493 46850 1.000 0.0000 0.2185 0.1065 0.3068
3 AN00090_AN00090 AN00544_AN00544 46803 1.000 0.0000 0.2199 0.1074 0.3080
4 AN00090_AN00090 AN00764_AN00764 46850 1.000 0.0000 0.2195 0.1098 0.3076
5 AN00090_AN00090 AN01125_AN01125 46803 1.000 0.0000 0.2166 0.1094 0.3034
6 AN00090_AN00090 AN01410_AN01410 46803 1.000 0.0000 0.2195 0.1125 0.3088
7 AN00090_AN00090 AN01971_AN01971 46803 1.000 0.0000 0.2196 0.1080 0.3081
  HomIBS0 Kinship IBD1Seg IBD2Seg PropIBD InfType Error
2 -0.9506 0.0059  0.0083  0.0000  0.0042  UN      0
3 -0.9541 0.0055  0.0038  0.0000  0.0019  UN      0
4 -0.9998 0.0000  0.0108  0.0000  0.0054  UN      0
5 -1.0201 -0.0023 0.0152  0.0000  0.0076  UN      0
6 -1.0505 -0.0058 0.0000  0.0000  0.0000  UN      0
7 -0.9673 0.0039  0.0053  0.0000  0.0027  UN      0

In [8]:
dim(king_ace)

[1] 3409550      15

In [9]:
sa_covar <- read.csv("ace_spark_total_covar.csv")

In [10]:
sa_covar <- sa_covar[sa_covar$sampleset == "ace", c("FID", "IID")]

In [11]:
sa_covar$ID1 <- sa_covar$IID
sa_covar$ID2 <- sa_covar$IID
sa_covar$FID1 <-sa_covar$FID
sa_covar$FID2 <-sa_covar$FID

In [12]:
ace_rel <- king_ace[king_ace$Kinship > 0, ]

In [13]:
dim(ace_rel)

[1] 678512     15

In [14]:
ace_2nd <- ace_rel[ace_rel$Kinship >= (1/8),]

In [15]:
dim(ace_2nd)

[1] 2346   15

In [16]:
ace_2nd <- left_join(ace_2nd, sa_covar[,c("ID1", "FID1")], by = "ID1")

In [17]:
ace_2nd <- left_join(ace_2nd, sa_covar[,c("ID2", "FID2")], by = "ID2")

In [18]:
head(ace_2nd)

  ID1               ID2               N_SNP Z0    Phi    HetHet IBS0   HetConc
1 AU009501_AU009501 AU009504_AU009504 46850 1.000 0.0000 0.2235 0.0002 0.3209
2 AU009502_AU009502 AU009504_AU009504 46850 1.000 0.0000 0.2400 0.0004 0.3446
3 AU020301_AU020301 AU020303_AU020303 46850 1.000 0.0000 0.2029 0.0443 0.3110
4 AU020302_AU020302 AU020303_AU020303 46850 1.000 0.0000 0.2143 0.0001 0.3342
5 AU020302_AU020302 AU020305_AU020305 46850 1.000 0.0000 0.2097 0.0003 0.3270
6 AU020302_AU020302 AU020306_AU020306 46847 1.000 0.0000 0.2133 0.0003 0.3334
  HomIBS0 Kinship IBD1Seg IBD2Seg PropIBD InfType Error FID1 FID2
1 -0.0008 0.2426  0.9942  0.0000  0.4971  PO      1     NA   NA
2 -0.0019 0.2553  0.9929  0.0000  0.4964  PO      1     NA   NA
3 -0.2792 0.1337  0.5300  0.0000  0.2650  2nd     1     NA   NA
4 -0.0007 0.2501  0.9999  0.0000  0.5000  PO      1     NA   NA
5 -0.0012 0.2458  0.9960  0.0000  0.4980  PO      1     NA   NA
6 -0.0014 0.2494  0.9986  0.0000  0.4993  PO      1     NA   NA

In [19]:
ace_2nd <- ace_2nd[ace_2nd$FID1 != ace_2nd$FID2, ]

In [20]:
dim(ace_2nd)

[1] 2346   17

In [41]:
ace_2nd

     ID1            ID2            N_SNP Z0    Phi    HetHet IBS0   HetConc
3    AU020301       AU020303       46850 1.000 0.0000 0.2029 0.0443 0.3110
1869 AU4882201      702-B-80312.01 46847 1.000 0.0000 0.2366 0.0003 0.3273
1874 AU4882202      702-B-80312.01 46847 1.000 0.0000 0.2598 0.0003 0.3396
1878 AU4882301      702-B-80312.01 46847 1.000 0.0000 0.2980 0.0238 0.4345
1881 AU4882302      702-B-80312.01 46847 1.000 0.0000 0.4898 0.0000 0.9974
1883 AU4882303      702-B-80312.01 46847 1.000 0.0000 0.2863 0.0330 0.4176
1884 AU4882304      702-B-80312.01 46847 1.000 0.0000 0.3160 0.0306 0.4690
1980 AU4988201      MH0180111      46844 1.000 0.0000 0.2423 0.0002 0.3457
1983 AU4988202      MH0180111      46844 1.000 0.0000 0.2203 0.0001 0.3201
1985 AU4988301      MH0180111      46844 1.000 0.0000 0.4652 0.0000 0.9973
1986 AU4988302      MH0180111      46844 1.000 0.0000 0.2820 0.0262 0.4408
2241 DNAID65        DNAID68        46799 1.000 0.0000 0.4635 0.0000 0.9997
2242 KP.BOS.400.03  KP864003       46844 1.000 0.0000 0.4652 0.0000 0.9996
2243 KP.SEA.809.04  KP789604       46844 1.000 0.0000 0.4109 0.0000 0.9991
2244 KP.SEA.810.03  KP524803       46844 1.000 0.0000 0.4889 0.0000 0.9994
2245 KP.SEA.816.03  KP180403       46844 1.000 0.0000 0.4694 0.0000 0.9998
2322 702-A-80359.01 702-B-80335.03 46841 1.000 0.0000 0.2353 0.0005 0.3329
2324 702-A-80359.02 702-B-80335.03 46841 1.000 0.0000 0.2315 0.0002 0.3314
2325 702-A-80359.04 702-B-80335.03 46841 1.000 0.0000 0.4681 0.0001 0.9974
     HomIBS0 Kinship IBD1Seg IBD2Seg PropIBD InfType Error FID1
3    -0.2792 0.1337  0.5300  0.0000  0.2650  2nd     1     AU020301
1869 -0.0014 0.2459  0.9940  0.0000  0.4970  PO      1     AU4882
1874 -0.0013 0.2528  0.9960  0.0000  0.4980  PO      1     AU4882
1878 -0.0869 0.2545  0.5539  0.2633  0.5403  FS      1     AU4882
1881 -0.0000 0.4993  0.0051  0.9938  0.9963  Dup/MZ  1     AU4882
1883 -0.1305 0.2266  0.5465  0.2067  0.4800  FS      1     AU4882
1884 -0.1073 0.2574  0.4413  0.3230  0.5436  FS      1     AU4882
1980 -0.0008 0.2565  0.9999  0.0000  0.5000  PO      1     AU4988
1983 -0.0005 0.2423  0.9999  0.0000  0.5000  PO      1     AU4988
1985 -0.0000 0.4993  0.0000  0.9973  0.9973  Dup/MZ  1     AU4988
1986 -0.1025 0.2491  0.5219  0.2304  0.4913  FS      1     AU4988
2241 -0.0000 0.4999  0.0000  0.9997  0.9997  Dup/MZ  1     DNAID65
2242 -0.0000 0.4999  0.0000  1.0000  1.0000  Dup/MZ  1     471-KP.BOS.400.03
2243 -0.0000 0.4998  0.0000  1.0000  1.0000  Dup/MZ  1     473-KP.SEA.809.04
2244 -0.0000 0.4998  0.0000  0.9991  0.9991  Dup/MZ  1     473-KP.SEA.810.03
2245 -0.0000 0.4999  0.0000  1.0000  1.0000  Dup/MZ  1     473-KP.SEA.816.03
2322 -0.0021 0.2487  0.9962  0.0000  0.4981  PO      1     702-A-80359
2324 -0.0008 0.2485  0.9992  0.0000  0.4996  PO      1     702-A-80359
2325 -0.0001 0.4992  0.0021  0.9954  0.9964  Dup/MZ  1     702-A-80359
     FID2
3    AU0203
1869 702-B-80312
1874 702-B-80312
1878 702-B-80312
1881 702-B-80312
1883 702-B-80312
1884 702-B-80312
1980 MH0180111
1983 MH0180111
1985 MH0180111
1986 MH0180111
2241 DNAID68
2242 KP8640
2243 KP7896
2244 KP5248
2245 KP1804
2322 702-B-80335
2324 702-B-80335
2325 702-B-80335

In [43]:
ace_final_rel <- ace_2nd[ace_2nd$InfType != "Dup/MZ",]

In [44]:
ace_final_rel

     ID1            ID2            N_SNP Z0    Phi    HetHet IBS0   HetConc
3    AU020301       AU020303       46850 1.000 0.0000 0.2029 0.0443 0.3110
1869 AU4882201      702-B-80312.01 46847 1.000 0.0000 0.2366 0.0003 0.3273
1874 AU4882202      702-B-80312.01 46847 1.000 0.0000 0.2598 0.0003 0.3396
1878 AU4882301      702-B-80312.01 46847 1.000 0.0000 0.2980 0.0238 0.4345
1883 AU4882303      702-B-80312.01 46847 1.000 0.0000 0.2863 0.0330 0.4176
1884 AU4882304      702-B-80312.01 46847 1.000 0.0000 0.3160 0.0306 0.4690
1980 AU4988201      MH0180111      46844 1.000 0.0000 0.2423 0.0002 0.3457
1983 AU4988202      MH0180111      46844 1.000 0.0000 0.2203 0.0001 0.3201
1986 AU4988302      MH0180111      46844 1.000 0.0000 0.2820 0.0262 0.4408
2322 702-A-80359.01 702-B-80335.03 46841 1.000 0.0000 0.2353 0.0005 0.3329
2324 702-A-80359.02 702-B-80335.03 46841 1.000 0.0000 0.2315 0.0002 0.3314
     HomIBS0 Kinship IBD1Seg IBD2Seg PropIBD InfType Error FID1
3    -0.2792 0.1337  0.5300  0.0000  0.2650  2nd     1     AU020301
1869 -0.0014 0.2459  0.9940  0.0000  0.4970  PO      1     AU4882
1874 -0.0013 0.2528  0.9960  0.0000  0.4980  PO      1     AU4882
1878 -0.0869 0.2545  0.5539  0.2633  0.5403  FS      1     AU4882
1883 -0.1305 0.2266  0.5465  0.2067  0.4800  FS      1     AU4882
1884 -0.1073 0.2574  0.4413  0.3230  0.5436  FS      1     AU4882
1980 -0.0008 0.2565  0.9999  0.0000  0.5000  PO      1     AU4988
1983 -0.0005 0.2423  0.9999  0.0000  0.5000  PO      1     AU4988
1986 -0.1025 0.2491  0.5219  0.2304  0.4913  FS      1     AU4988
2322 -0.0021 0.2487  0.9962  0.0000  0.4981  PO      1     702-A-80359
2324 -0.0008 0.2485  0.9992  0.0000  0.4996  PO      1     702-A-80359
     FID2
3    AU0203
1869 702-B-80312
1874 702-B-80312
1878 702-B-80312
1883 702-B-80312
1884 702-B-80312
1980 MH0180111
1983 MH0180111
1986 MH0180111
2322 702-B-80335
2324 702-B-80335

In [45]:
write_csv(ace_final_rel, "ace_unlisted_relatives.csv")