In [ ]:
# wget https://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/PGS000327/ScoringFiles/PGS000327.txt.gz
# gunzip PGS000327.txt.gz

In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [9]:

# Replace 'your_score_file.txt' with the actual path to your score file
file_path <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/PGS000327.txt"

# Read the score file
score_data <- read.table(file_path, header = TRUE, sep = "\t", stringsAsFactors = FALSE)

In [10]:
head(score_data)

  rsID        chr_name chr_position effect_allele other_allele effect_weight
1 rs113901932 8        100228085    A             G            -0.0598031
2 rs151150581 8        100422898    T             C             0.0483043
3 rs76228276  8        100638095    A             C            -0.0610991
4 rs13260744  8        100831260    A             G            -0.0456984
5 rs7832556   8        100923156    A             G             0.0259016
6 rs7830618   8        100926037    T             C            -0.0382004
  variant_description
1
2
3
4
5
6

In [11]:
colnames(score_data)

[1] "rsID"                "chr_name"            "chr_position"
[4] "effect_allele"       "other_allele"        "effect_weight"
[7] "variant_description"

In [12]:
colnames(score_data) <- c('rsID', 'CHROM', 'POS', 'ALT', 'REF', 'WEIGHT', 'variant_description')

In [13]:
score_data$snp <- paste(score_data$CHROM, score_data$POS, score_data$REF, score_data$ALT, sep = ":")

In [14]:
head(score_data)

  rsID        CHROM POS       ALT REF WEIGHT     variant_description
1 rs113901932 8     100228085 A   G   -0.0598031
2 rs151150581 8     100422898 T   C    0.0483043
3 rs76228276  8     100638095 A   C   -0.0610991
4 rs13260744  8     100831260 A   G   -0.0456984
5 rs7832556   8     100923156 A   G    0.0259016
6 rs7830618   8     100926037 T   C   -0.0382004
  snp
1 8:100228085:G:A
2 8:100422898:C:T
3 8:100638095:C:A
4 8:100831260:G:A
5 8:100923156:G:A
6 8:100926037:C:T

In [15]:
write_table <- score_data[,c('snp', 'CHROM', 'POS', 'REF', 'ALT', 'WEIGHT')]

In [16]:
head(write_table)

  snp             CHROM POS       REF ALT WEIGHT
1 8:100228085:G:A 8     100228085 G   A   -0.0598031
2 8:100422898:C:T 8     100422898 C   T    0.0483043
3 8:100638095:C:A 8     100638095 C   A   -0.0610991
4 8:100831260:G:A 8     100831260 G   A   -0.0456984
5 8:100923156:G:A 8     100923156 G   A    0.0259016
6 8:100926037:C:T 8     100926037 C   T   -0.0382004

In [17]:
# Specify the file path for writing
file_path <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/grove_hg19_asd.tsv"

# Write the data frame to a TSV file without row names
write.table(write_table, file = file_path, sep = "\t", row.names = FALSE, col.names = TRUE)