In [1]:
library(dplyr)
library(biomaRt)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [11]:
getwd()

[1] "/u/project/pasaniuc/afcarrol/Projects/20231018_prscs_scores"

In [2]:
getwd()

[1] "/u/project/pasaniuc/afcarrol/Projects/20231018_prscs_scores"

In [3]:
raw_grove <- read.table('/u/project/pasaniuc/afcarrol/Projects/20231018_prscs_scores/iPSYCH-PGC_ASD_Nov2017.txt', sep="\t")

In [4]:
head(raw_grove)

  V1  V2         V3        V4 V5 V6    V7      V8     V9
1 CHR SNP        BP        A1 A2 INFO  OR      SE     P
2 8   rs62513865 101592213 T  C  0.949 1.00652 0.027  0.8086
3 8   rs79643588 106973048 A  G  0.997 1.01786 0.024  0.4606
4 8   rs17396518 108690829 T  G  0.987 0.96127 0.014  0.004647
5 8   rs983166   108681675 A  C  0.998 0.97990 0.0139 0.1452
6 8   rs28842593 103044620 T  C  0.857 0.99591 0.0203 0.8415

In [5]:
# Set the column names using the values from the first row
colnames(raw_grove) <- unlist(raw_grove[1,])

# Remove the first row (optional if you don't need it anymore)
raw_grove <- raw_grove[-1,]

In [6]:
head(raw_grove)

  CHR SNP        BP        A1 A2 INFO  OR      SE     P
2 8   rs62513865 101592213 T  C  0.949 1.00652 0.027  0.8086
3 8   rs79643588 106973048 A  G  0.997 1.01786 0.024  0.4606
4 8   rs17396518 108690829 T  G  0.987 0.96127 0.014  0.004647
5 8   rs983166   108681675 A  C  0.998 0.97990 0.0139 0.1452
6 8   rs28842593 103044620 T  C  0.857 0.99591 0.0203 0.8415
7 8   rs35107696 109712249 A  AT 0.999 1.01308 0.0165 0.4302

In [7]:
grove_table <- raw_grove[,c("SNP", "A1", "A2", "OR", "P")]

In [8]:
write.table(grove_table, file = "grove_gwas.txt", sep = "\t", row.names = FALSE)

In [9]:
rm(grove_table, raw_grove)

In [3]:
raw_spark <- read.table('/u/project/geschwind/vishakha/Projects/GWAS_AFR/GWAS_SAIGE_AFR_11M_var/SAIGE_RESULT/SPARK_AA_marker_chr1-22_vcf.txt', sep="\t")

In [15]:
head(raw_spark)

  V1  V2     V3          V4      V5      V6         V7         V8
1 CHR POS    MarkerID    Allele1 Allele2 AC_Allele2 AF_Allele2 MissingRate
2 1   858952 rs12127425  G       A       1064       0.113578   0
3 1   859842 rs12131377  C       G       487        0.0519855  0
4 1   863421 rs12132517  G       A       482        0.0514518  0
5 1   864119 rs147634896 T       C       485        0.051772   0
6 1   866281 rs12132974  C       T       440        0.0469684  0
  V9        V10      ⋯ V14          V15    V16       V17       V18    V19
1 BETA      SE       ⋯ p.value.NA   Is.SPA AF_case   AF_ctrl   N_case N_ctrl
2 0.0332094 0.122293 ⋯ 7.859630E-01 false  0.11013   0.117902  2606   2078
3 0.0816997 0.174133 ⋯ 6.389405E-01 false  0.0519954 0.0519731 2606   2078
4 0.0954879 0.175393 ⋯ 5.861508E-01 false  0.0514198 0.0514918 2606   2078
5 0.0778062 0.175215 ⋯ 6.569981E-01 false  0.0518035 0.0517324 2606   2078
6 0.133888  0.183498 ⋯ 4.656069E-01 false  0.0477744 0.0459577 2606   2078
  V20        V21        V22        V23
1 N_case_hom N_case_het N_ctrl_hom N_ctrl_het
2 22         530        35         420
3 4          263        7          202
4 4          260        7          200
5 4          262        7          201
6 3          243        5          181

In [4]:
# Set the column names using the values from the first row
colnames(raw_spark) <- unlist(raw_spark[1,])

# Remove the first row (optional if you don't need it anymore)
raw_spark <- raw_spark[-1,]

In [5]:
head(raw_spark)

  CHR POS    MarkerID    Allele1 Allele2 AC_Allele2 AF_Allele2 MissingRate
2 1   858952 rs12127425  G       A       1064       0.113578   0
3 1   859842 rs12131377  C       G       487        0.0519855  0
4 1   863421 rs12132517  G       A       482        0.0514518  0
5 1   864119 rs147634896 T       C       485        0.051772   0
6 1   866281 rs12132974  C       T       440        0.0469684  0
7 1   866300 rs12134490  A       C       440        0.0469684  0
  BETA      SE       ⋯ p.value.NA   Is.SPA AF_case   AF_ctrl   N_case N_ctrl
2 0.0332094 0.122293 ⋯ 7.859630E-01 false  0.11013   0.117902  2606   2078
3 0.0816997 0.174133 ⋯ 6.389405E-01 false  0.0519954 0.0519731 2606   2078
4 0.0954879 0.175393 ⋯ 5.861508E-01 false  0.0514198 0.0514918 2606   2078
5 0.0778062 0.175215 ⋯ 6.569981E-01 false  0.0518035 0.0517324 2606   2078
6 0.133888  0.183498 ⋯ 4.656069E-01 false  0.0477744 0.0459577 2606   2078
7 0.133888  0.183498 ⋯ 4.656069E-01 false  0.0477744 0.0459577 2606   2078
  N_case_hom N_case_het N_ctrl_hom N_ctrl_het
2 22         530        35         420
3 4          263        7          202
4 4          260        7          200
5 4          262        7          201
6 3          243        5          181
7 3          243        5          181

In [18]:
colnames(raw_spark)

 [1] "CHR"         "POS"         "MarkerID"    "Allele1"     "Allele2"
 [6] "AC_Allele2"  "AF_Allele2"  "MissingRate" "BETA"        "SE"
[11] "Tstat"       "var"         "p.value"     "p.value.NA"  "Is.SPA"
[16] "AF_case"     "AF_ctrl"     "N_case"      "N_ctrl"      "N_case_hom"
[21] "N_case_het"  "N_ctrl_hom"  "N_ctrl_het"

In [6]:
spark_chr_pos <- raw_spark[,c("CHR", "POS")]

In [7]:
head(spark_chr_pos)

  CHR POS
2 1   858952
3 1   859842
4 1   863421
5 1   864119
6 1   866281
7 1   866300

In [9]:
write.table(spark_chr_pos, file = "spark_gwas_cp.txt", sep = "\t", row.names = FALSE, col.names = FALSE)

In [19]:
spark_table <- raw_spark[,c("MarkerID", "Allele1", "Allele2", "BETA", "p.value")]

In [20]:
head(spark_table)

  MarkerID    Allele1 Allele2 BETA      p.value
2 rs12127425  G       A       0.0332094 7.859630E-01
3 rs12131377  C       G       0.0816997 6.389405E-01
4 rs12132517  G       A       0.0954879 5.861508E-01
5 rs147634896 T       C       0.0778062 6.569981E-01
6 rs12132974  C       T       0.133888  4.656069E-01
7 rs12134490  A       C       0.133888  4.656069E-01

In [21]:
colnames(spark_table) <- c("SNP", "A1", "A2", "BETA", "P")

In [3]:
head(spark_table)

ERROR: Error in head(spark_table): object 'spark_table' not found

In [23]:
write.table(spark_table, file = "spark_gwas.txt", sep = "\t", row.names = FALSE)

In [ ]:
rm(raw_spark)

In [2]:
spark_table <- read.table("spark_gwas.txt")

In [3]:
# Set the column names using the values from the first row
colnames(spark_table) <- unlist(spark_table[1,])

# Remove the first row (optional if you don't need it anymore)
spark_table <- spark_table[-1,]

In [4]:
head(spark_table)

  SNP         A1 A2 BETA      P
2 rs12127425  G  A  0.0332094 7.859630E-01
3 rs12131377  C  G  0.0816997 6.389405E-01
4 rs12132517  G  A  0.0954879 5.861508E-01
5 rs147634896 T  C  0.0778062 6.569981E-01
6 rs12132974  C  T  0.133888  4.656069E-01
7 rs12134490  A  C  0.133888  4.656069E-01

In [11]:
# Set the Mart and dataset for hg19
#ensembl <- useEnsembl(biomart = "ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl", host = 'www.ensembl.org', version = "GRCh37")

# Define a list of rsIDs

Possible SSL connectivity problems detected.
Please report this issue at https://github.com/grimbough/biomaRt/issues
Error in curl::curl_fetch_memory(url, handle = handle) :
  Peer certificate cannot be authenticated with given CA certificates: [uswest.ensembl.org] Peer's Certificate has expired.

In [13]:
ensembl <- useEnsembl(biomart = "ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl", host = 'useast.ensembl.org', version = "GRCh37")

In [5]:
rsids <- spark_table$SNP

In [ ]:

snpmart = useEnsembl(biomart = "snp", dataset="hsapiens_snp", version = "GRCh37")

# Get the chromosome, position, reference allele, and alternate allele for each rsID
snp_info <- getBM(attributes = c("refsnp_id", "chr_name", "chrom_start", "allele", "minor_allele"),
                  filters = "snp_filter", values = rsids, mart = snpmart)

Batch submitting query [-------------------------------]   0% eta:  5d

Batch submitting query [-------------------------------]   0% eta:  4d

Batch submitting query [-------------------------------]   1% eta:  4d

In [18]:
att <- listAttributes(ensembl)

In [19]:
View(att)

     name
1    ensembl_gene_id
2    ensembl_gene_id_version
3    ensembl_transcript_id
4    ensembl_transcript_id_version
5    ensembl_peptide_id
6    ensembl_peptide_id_version
7    ensembl_exon_id
8    description
9    chromosome_name
10   start_position
11   end_position
12   strand
13   band
14   transcript_start
15   transcript_end
16   transcription_start_site
17   transcript_length
18   transcript_tsl
19   transcript_gencode_basic
20   transcript_appris
21   transcript_is_canonical
22   transcript_mane_select
23   transcript_mane_plus_clinical
24   external_gene_name
25   external_gene_source
26   external_transcript_name
27   external_transcript_source_name
28   transcript_count
29   percentage_gene_gc_content
30   gene_biotype
⋮    ⋮
3140 5_utr_end
3141 3_utr_start
3142 3_utr_end
3143 ensembl_transcript_id
3144 ensembl_transcript_id_version
3145 ensembl_peptide_id
3146 ensembl_peptide_id_version
3147 transcript_biotype
3148 transcript_version
3149 peptide_version
3150 strand
3151 transcript_start
3152 transcript_end
3153 transcription_start_site
3154 transcript_length
3155 cds_length
3156 cds_start
3157 cds_end
3158 ensembl_exon_id
3159 exon_chrom_start
3160 exon_chrom_end
3161 strand
3162 rank
3163 phase
3164 end_phase
3165 cdna_coding_start
3166 cdna_coding_end
3167 genomic_coding_start
3168 genomic_coding_end
3169 is_constitutive
     description                                  page
1    Gene stable ID                               feature_page
2    Gene stable ID version                       feature_page
3    Transcript stable ID                         feature_page
4    Transcript stable ID version                 feature_page
5    Protein stable ID                            feature_page
6    Protein stable ID version                    feature_page
7    Exon stable ID                               feature_page
8    Gene description                             feature_page
9    Chromosome/scaffold name                     feature_page
10   Gene start (bp)                              feature_page
11   Gene end (bp)                                feature_page
12   Strand                                       feature_page
13   Karyotype band                               feature_page
14   Transcript start (bp)                        feature_page
15   Transcript end (bp)                          feature_page
16   Transcription start site (TSS)               feature_page
17   Transcript length (including UTRs and CDS)   feature_page
18   Transcript support level (TSL)               feature_page
19   GENCODE basic annotation                     feature_page
20   APPRIS annotation                            feature_page
21   Ensembl Canonical                            feature_page
22   RefSeq match transcript (MANE Select)        feature_page
23   RefSeq match transcript (MANE Plus Clinical) feature_page
24   Gene name                                    feature_page
25   Source of gene name                          feature_page
26   Transcript name                              feature_page
27   Source of transcript name                    feature_page
28   Transcript count                             feature_page
29   Gene % GC content                            feature_page
30   Gene type                                    feature_page
⋮    ⋮                                            ⋮
3140 5' UTR end                                   sequences
3141 3' UTR start                                 sequences
3142 3' UTR end                                   sequences
3143 Transcript stable ID                         sequences
3144 Transcript stable ID version                 sequences
3145 Protein stable ID                            sequences
3146 Protein stable ID version                    sequences
3147 Transcript type                              sequences
3148 Version (transcript)                         sequences
3149 Version (protein)                            sequences
3150 Strand                                       sequences
3151 Transcript start (bp)                        sequences
3152 Transcript end (bp)                          sequences
3153 Transcription start site (TSS)               sequences
3154 Transcript length (including UTRs and CDS)   sequences
3155 CDS Length                                   sequences
3156 CDS start                                    sequences
3157 CDS end                                      sequences
3158 Exon stable ID                               sequences
3159 Exon region start (bp)                       sequences
3160 Exon region end (bp)                         sequences
3161 Strand                                       sequences
3162 Exon rank in transcript                      sequences
3163 Start phase                                  sequences
3164 End phase                                    sequences
3165 cDNA coding start                            sequences
3166 cDNA coding end                              sequences
3167 Genomic coding start                         sequences
3168 Genomic coding end                           sequences
3169 Constitutive exon                            sequences

In [21]:
write.table(att, file = "ens_att.txt", sep = "\t", row.names = FALSE)