In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
psam_df <- read.table("//u/project/geschwind/shared/GenomicDatasets-processed/ACE-ANALYSIS/freeze0/SPARK/imputed/chr3.psam")

In [5]:
head(psam_df)

  V1                  V2
1 SF0000003_SP0000003 NA
2 SF0030253_SP0000006 NA
3 SF0031322_SP0000007 NA
4 SF0013567_SP0000009 NA
5 SF0024927_SP0000014 NA
6 SF0020550_SP0000015 NA

In [5]:
covar <- read.csv("spark_covar_saige.csv")

In [8]:
head(covar)

  X   IID                 Age Sex ASD PC1       PC2        PC3
1 112 SF0000914_SP0025844 497 1   1   162.90333  0.5126609 -5.6791765
2 195 SF0001583_SP0001583  60 1   2   129.97302 13.5162719 -9.4129636
3 196 SF0001583_SP0001720 453 1   1   113.52600 22.4859639 -8.6766201
4 197 SF0001583_SP0001536 398 2   1   159.53368 -0.4437008 -5.2597911
5 371 SF0003386_SP0003414  23 1   2    72.62620 33.4963693 -2.7121802
6 372 SF0003386_SP0003386  54 1   2    70.20508 33.6585374 -0.8303692
  PC4        PC5       PC6        PC7         PC8        PC9         PC10
1  -1.724073 -4.009686  0.6606196  -9.2171288   8.101596  0.04062518  2.3290313
2  -6.202651 -3.396206 -0.3216511  -0.8951926   4.417643 -1.75147069 -2.8047637
3  -8.905824 -2.270763  1.4299533  -3.3414043   7.579669 -1.61016047 -5.3114287
4  -3.767932 -2.489947  0.1155772  -4.6226349   7.186049  1.30890580 -0.2917196
5 -12.474572 25.716398 -5.3438820 -19.6948795 -39.432922  0.76713408  3.2403588
6 -15.129232 29.138770 -4.7567959 -21.8981683 -41.379100 -0.59442922  6.5259796

In [10]:
head(covar$IID)

[1] "SF0000914_SP0025844" "SF0001583_SP0001583" "SF0001583_SP0001720"
[4] "SF0001583_SP0001536" "SF0003386_SP0003414" "SF0003386_SP0003386"

In [4]:
length(unique(covar$IID))

[1] 3766

In [7]:
# Elements in list1 but not in list2
in_csv_only <- covar$IID[!(covar$IID %in% psam_df$V1)]

# Elements in list2 but not in list1
in_vcf_only <- psam_df$V1[!(psam_df$V1 %in% covar$IID)]

In [8]:
in_csv_only

character(0)

In [9]:
length(in_vcf_only)

[1] 64550

In [2]:
fam_f <- read.table("/u/project/gandalm/shared/GenomicDatasets-processed/SPARK/genotype/iWES/TOPMed_imputed/SPARKiwes_TopMed_chr1.22_rsID.MikeDB_SPARKdb155.fam")

In [3]:
head(fam_f)

  V1        V2        V3 V4 V5 V6
1 SF0000003 SP0000003 0  0  0  -9
2 SF0000017 SP0000017 0  0  0  -9
3 SF0000027 SP0000027 0  0  0  -9
4 SF0000027 SP0000034 0  0  0  -9
5 SF0000027 SP0000051 0  0  0  -9
6 SF0000027 SP0000063 0  0  0  -9

In [9]:
covar$IID <- sub(".*_", "", covar$IID)

In [10]:
length(covar$IID[!(covar$IID %in% fam_f$V2)])

[1] 2

In [11]:
head(covar$IID[!(covar$IID %in% fam_f$V2)])

[1] "SP0127558" "SP0329741"

In [12]:
spark_afr_list <- covar$IID[(covar$IID %in% fam_f$V2)]

In [13]:
length(spark_afr_list)

[1] 3764

In [15]:
head(spark_afr_list)

[1] "SP0025844" "SP0001583" "SP0001720" "SP0001536" "SP0003414" "SP0003386"

In [16]:
iid_df <- fam_f[fam_f$V2 %in% covar$IID, c("V1", "V2")]

In [17]:
colnames(iid_df) <- c("FID", "IID")

In [18]:
head(iid_df)

    FID       IID
116 SF0000914 SP0025844
202 SF0001583 SP0001536
203 SF0001583 SP0001583
204 SF0001583 SP0001720
386 SF0003386 SP0003386
387 SF0003386 SP0003414

In [19]:
dim(iid_df)

[1] 3764    2

In [21]:
write.table(iid_df, file = "iid_list.txt", sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)

In [14]:
#write.table(spark_afr_list, file = "spark_afr_sub.txt", row.names = FALSE, col.names = FALSE, quote = FALSE)

In [22]:
head(iid_df)

    FID       IID
116 SF0000914 SP0025844
202 SF0001583 SP0001536
203 SF0001583 SP0001583
204 SF0001583 SP0001720
386 SF0003386 SP0003386
387 SF0003386 SP0003414

In [23]:
covar_final <- left_join(iid_df, covar, by="IID")

In [24]:
head(covar_final)

  FID       IID       X   Age Sex ASD PC1       PC2        PC3
1 SF0000914 SP0025844 112 497 1   1   162.90333  0.5126609 -5.6791765
2 SF0001583 SP0001536 197 398 2   1   159.53368 -0.4437008 -5.2597911
3 SF0001583 SP0001583 195  60 1   2   129.97302 13.5162719 -9.4129636
4 SF0001583 SP0001720 196 453 1   1   113.52600 22.4859639 -8.6766201
5 SF0003386 SP0003386 372  54 1   2    70.20508 33.6585374 -0.8303692
6 SF0003386 SP0003414 371  23 1   2    72.62620 33.4963693 -2.7121802
  PC4        PC5       PC6        PC7         PC8        PC9         PC10
1  -1.724073 -4.009686  0.6606196  -9.2171288   8.101596  0.04062518  2.3290313
2  -3.767932 -2.489947  0.1155772  -4.6226349   7.186049  1.30890580 -0.2917196
3  -6.202651 -3.396206 -0.3216511  -0.8951926   4.417643 -1.75147069 -2.8047637
4  -8.905824 -2.270763  1.4299533  -3.3414043   7.579669 -1.61016047 -5.3114287
5 -15.129232 29.138770 -4.7567959 -21.8981683 -41.379100 -0.59442922  6.5259796
6 -12.474572 25.716398 -5.3438820 -19.6948795 -39.432922  0.76713408  3.2403588

In [25]:
head(covar)

  X   IID       Age Sex ASD PC1       PC2        PC3        PC4
1 112 SP0025844 497 1   1   162.90333  0.5126609 -5.6791765  -1.724073
2 195 SP0001583  60 1   2   129.97302 13.5162719 -9.4129636  -6.202651
3 196 SP0001720 453 1   1   113.52600 22.4859639 -8.6766201  -8.905824
4 197 SP0001536 398 2   1   159.53368 -0.4437008 -5.2597911  -3.767932
5 371 SP0003414  23 1   2    72.62620 33.4963693 -2.7121802 -12.474572
6 372 SP0003386  54 1   2    70.20508 33.6585374 -0.8303692 -15.129232
  PC5       PC6        PC7         PC8        PC9         PC10
1 -4.009686  0.6606196  -9.2171288   8.101596  0.04062518  2.3290313
2 -3.396206 -0.3216511  -0.8951926   4.417643 -1.75147069 -2.8047637
3 -2.270763  1.4299533  -3.3414043   7.579669 -1.61016047 -5.3114287
4 -2.489947  0.1155772  -4.6226349   7.186049  1.30890580 -0.2917196
5 25.716398 -5.3438820 -19.6948795 -39.432922  0.76713408  3.2403588
6 29.138770 -4.7567959 -21.8981683 -41.379100 -0.59442922  6.5259796

In [26]:
length(unique(covar_final$IID))

[1] 3764

In [27]:
covar_final <- covar_final[, !names(covar_final) %in% "X", drop = FALSE]

In [28]:
head(covar_final)

  FID       IID       Age Sex ASD PC1       PC2        PC3        PC4
1 SF0000914 SP0025844 497 1   1   162.90333  0.5126609 -5.6791765  -1.724073
2 SF0001583 SP0001536 398 2   1   159.53368 -0.4437008 -5.2597911  -3.767932
3 SF0001583 SP0001583  60 1   2   129.97302 13.5162719 -9.4129636  -6.202651
4 SF0001583 SP0001720 453 1   1   113.52600 22.4859639 -8.6766201  -8.905824
5 SF0003386 SP0003386  54 1   2    70.20508 33.6585374 -0.8303692 -15.129232
6 SF0003386 SP0003414  23 1   2    72.62620 33.4963693 -2.7121802 -12.474572
  PC5       PC6        PC7         PC8        PC9         PC10
1 -4.009686  0.6606196  -9.2171288   8.101596  0.04062518  2.3290313
2 -2.489947  0.1155772  -4.6226349   7.186049  1.30890580 -0.2917196
3 -3.396206 -0.3216511  -0.8951926   4.417643 -1.75147069 -2.8047637
4 -2.270763  1.4299533  -3.3414043   7.579669 -1.61016047 -5.3114287
5 29.138770 -4.7567959 -21.8981683 -41.379100 -0.59442922  6.5259796
6 25.716398 -5.3438820 -19.6948795 -39.432922  0.76713408  3.2403588

In [30]:
write.csv(covar_final, file="spark_afr_covar_2.csv", row.names=F)