In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [45]:
one_kg <- read.table('/u/project/pasaniuc/afcarrol/Projects/20230930_1kg_variants/1kg_var.snplist')

In [46]:
head(one_kg)

  V1
1 1:58814:G:A
2 1:792461:G:A
3 1:817341:A:G
4 1:823656:G:A
5 1:858952:G:A
6 1:894801:A:G

In [47]:
one_kg$id <- paste("chr", one_kg$V1, sep = "")

In [48]:
head(one_kg)

  V1           id
1 1:58814:G:A  chr1:58814:G:A
2 1:792461:G:A chr1:792461:G:A
3 1:817341:A:G chr1:817341:A:G
4 1:823656:G:A chr1:823656:G:A
5 1:858952:G:A chr1:858952:G:A
6 1:894801:A:G chr1:894801:A:G

In [49]:
# Split the entries by colon and store the result in a new data frame
one_kg_2 <- as.data.frame(do.call(rbind, strsplit(one_kg$V1, ":")))

# Rename the columns
colnames(one_kg_2) <- c("chrom", "pos", "ref", "alt")

In [7]:
imputed_data <- read.table('/u/project/geschwind/shared/GenomicDatasets-processed/Imputed/total_vcfs_r2_0.8/combined/merged_output_2_var.txt')

In [8]:
head(imputed_data)

  V1    V2    V3                V4  V5
1 chr10 12040 chr10:12040:G:A   G   A
2 chr10 14470 chr10:14470:C:T   C   T
3 chr10 31093 chr10:31093:GAC:G GAC G
4 chr10 36953 chr10:36953:G:C   G   C
5 chr10 37005 chr10:37005:C:A   C   A
6 chr10 40467 chr10:40467:A:C   A   C

In [38]:
final_snps <- imputed_data[imputed_data$V3 %in% one_kg$id ,]

In [50]:
sum(imputed_data$V3 %in% one_kg$id)

[1] 426243

In [39]:
head(final_snps)

     V1 V2 V3 V4 V5

In [35]:
deno <- read.table("20231203_ACE_denovos.txt", sep = "\t")
colnames(deno) <- deno[1, ]
deno <- deno[-1, ]
rownames(deno) <- NULL

In [36]:
head(deno)

  variant                                                         sampleID
1 chr1:1041678:CGCTCCGGCCAGTGCCAGGGTCGAGGTGAGCGGCTCCCCCGGGGGAGG:C AU4690305
2 chr1:11847267:C:T                                               AU3937301
3 chr1:13342921:T:C                                               AU1920301
4 chr1:13342933:G:T                                               AU1920301
5 chr1:13420931:C:T                                               AU1389305
6 chr1:23971953:C:A                                               AU4992303
  role    father_sampleID mother_sampleID gene
1 Sibling AU4690201       AU4690202       AGRN
2 Sibling AU3937201       AU3937202       NPPA
3 Sibling AU1920201       AU1920202       PRAMEF14
4 Sibling AU1920201       AU1920202       PRAMEF14
5 Sibling AU1389201       AU1389202       PRAMEF20
6 Sibling AU4992201       AU4992202       SRSF10
  consequence
1 ["splice_donor_variant","coding_sequence_variant","intron_variant"]
2 ["missense_variant"]
3 ["synonymous_variant"]
4 ["synonymous_variant"]
5 ["synonymous_variant"]
6 ["missense_variant"]
  hgvsc                                 isPTV isMIS isSYN isIndel
1 ENST00000379370.6:c.1177+4_1177+50del TRUE  FALSE FALSE TRUE
2 ENST00000376480.7:c.296G>A            FALSE TRUE  FALSE FALSE
3 ENST00000334600.6:c.1032A>G           FALSE FALSE TRUE  FALSE
4 ENST00000334600.6:c.1020C>A           FALSE FALSE TRUE  FALSE
5 ENST00000316412.9:c.1101C>T           FALSE FALSE TRUE  FALSE
6 ENST00000492112.2:c.334G>T            FALSE TRUE  FALSE FALSE
  gnomad_non_neuro_AF gnomad_non_neuro_AF_AFR MPC
1 0                   0                       .
2 1.46E-05            0                       0.023648
3 3.22E-05            0.00040783              .
4 8.19E-05            0.00011366              .
5 .                   .                       .
6 .                   .                       .

In [54]:
dim(deno)

[1] 471  15

In [51]:
sum(deno$variant %in% one_kg$id)

[1] 0

In [52]:
sum(deno$variant %in% imputed_data$V3)

[1] 4

In [63]:
deno$test_swap <- gsub("^(.*:)([ACGT]+):([ACGT]+)$", "\\1\\3:\\2", deno$variant)

In [64]:
head(deno[,c("test_swap", "variant")])

  test_swap
1 chr1:1041678:C:CGCTCCGGCCAGTGCCAGGGTCGAGGTGAGCGGCTCCCCCGGGGGAGG
2 chr1:11847267:T:C
3 chr1:13342921:C:T
4 chr1:13342933:T:G
5 chr1:13420931:T:C
6 chr1:23971953:A:C
  variant
1 chr1:1041678:CGCTCCGGCCAGTGCCAGGGTCGAGGTGAGCGGCTCCCCCGGGGGAGG:C
2 chr1:11847267:C:T
3 chr1:13342921:T:C
4 chr1:13342933:G:T
5 chr1:13420931:C:T
6 chr1:23971953:C:A

In [65]:
sum(deno$test_swap %in% imputed_data$V3)

[1] 0

In [66]:
deno[deno$variant %in% imputed_data$V3,]$test_swap

[1] "chr6:75702944:A:AAAT" "chr9:127393217:T:C"   "chr14:22492880:T:G"
[4] "chr15:38481331:T:C"