In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [ ]:
#Subpopulation order/codes: CEU=0\tYRI=1 msp files ace

In [2]:
#vars of interest

raw_vars <- read.table('20231203_ACE_denovos.txt', sep = "\t")

# Make the first row as column names
colnames(raw_vars) <- raw_vars[1, ]

# Remove the first row
raw_vars <- raw_vars[-1, ]

raw_vars$sampleID <- paste0(raw_vars$sampleID, "_", raw_vars$sampleID)

In [3]:
head(raw_vars)

  variant
2 chr1:1041678:CGCTCCGGCCAGTGCCAGGGTCGAGGTGAGCGGCTCCCCCGGGGGAGG:C
3 chr1:11847267:C:T
4 chr1:13342921:T:C
5 chr1:13342933:G:T
6 chr1:13420931:C:T
7 chr1:23971953:C:A
  sampleID            role    father_sampleID mother_sampleID gene
2 AU4690305_AU4690305 Sibling AU4690201       AU4690202       AGRN
3 AU3937301_AU3937301 Sibling AU3937201       AU3937202       NPPA
4 AU1920301_AU1920301 Sibling AU1920201       AU1920202       PRAMEF14
5 AU1920301_AU1920301 Sibling AU1920201       AU1920202       PRAMEF14
6 AU1389305_AU1389305 Sibling AU1389201       AU1389202       PRAMEF20
7 AU4992303_AU4992303 Sibling AU4992201       AU4992202       SRSF10
  consequence
2 ["splice_donor_variant","coding_sequence_variant","intron_variant"]
3 ["missense_variant"]
4 ["synonymous_variant"]
5 ["synonymous_variant"]
6 ["synonymous_variant"]
7 ["missense_variant"]
  hgvsc                                 isPTV isMIS isSYN isIndel
2 ENST00000379370.6:c.1177+4_1177+50del TRUE  FALSE FALSE TRUE
3 ENST00000376480.7:c.296G>A            FALSE TRUE  FALSE FALSE
4 ENST00000334600.6:c.1032A>G           FALSE FALSE TRUE  FALSE
5 ENST00000334600.6:c.1020C>A           FALSE FALSE TRUE  FALSE
6 ENST00000316412.9:c.1101C>T           FALSE FALSE TRUE  FALSE
7 ENST00000492112.2:c.334G>T            FALSE TRUE  FALSE FALSE
  gnomad_non_neuro_AF gnomad_non_neuro_AF_AFR MPC
2 0                   0                       .
3 1.46E-05            0                       0.023648
4 3.22E-05            0.00040783              .
5 8.19E-05            0.00011366              .
6 .                   .                       .
7 .                   .                       .

In [5]:
length(unique(raw_vars$sampleID))

[1] 230

In [6]:
length(unique(raw_vars$variant))

[1] 466

In [4]:
# Group by variant and summarize the sampleIDs into a list
var_indv <- raw_vars %>%
  group_by(variant) %>%
  summarize(sampleIDs = list(unique(sampleID)))

In [51]:
var_indv[27,]

  variant           sampleIDs
1 chr1:27997351:C:A AU1505302_AU1505302, AU1505303_AU1505303

In [16]:
colnames(var_indv)

[1] "variant"   "sampleIDs"

In [2]:
var_indv

ERROR: Error in eval(expr, envir, enclos): object 'var_indv' not found

In [52]:
unlist(var_indv[var_indv$variant == "chr1:27997351:C:A",]$sampleIDs)

[1] "AU1505302_AU1505302" "AU1505303_AU1505303"

In [53]:
col__test <- c(outer(unlist(var_indv[27,]$sampleIDs), c(".0", ".1"), paste0))

In [46]:
typeof(c(unlist(outer(unlist(var_indv[27,]$sampleIDs), c(".0", ".1"), paste0))))

[1] "character"

In [54]:
c(unlist(outer(unlist(var_indv[27,]$sampleIDs), c(".0", ".1"), paste0)))[1]

[1] "AU1505302_AU1505302.0"

In [28]:
col__test

[1] "AU1505302.0" "AU1505303.0" "AU1505302.1" "AU1505303.1"

In [25]:
test <- c("variant", "sampleIDs")

In [26]:
head(var_indv[,test])

  variant                                                         sampleIDs
1 chr1:1041678:CGCTCCGGCCAGTGCCAGGGTCGAGGTGAGCGGCTCCCCCGGGGGAGG:C AU4690305
2 chr1:109171944:C:A                                              AU4726301
3 chr1:109264138:C:T                                              DG1087-305
4 chr1:109264888:A:G                                              AU4654301
5 chr1:11847267:C:T                                               AU3937301
6 chr1:1233007:G:A                                                DG1339-302

In [38]:
head(msp)

ERROR: Error in head(msp): object 'msp' not found

In [11]:
"AU1505302" %in% unlist(var_indv[var_indv$variant == "chr1:27997351:C:A",]$sampleIDs)

[1] TRUE

In [9]:
head(raw_vars)

  variant                                                         sampleID
2 chr1:1041678:CGCTCCGGCCAGTGCCAGGGTCGAGGTGAGCGGCTCCCCCGGGGGAGG:C AU4690305
3 chr1:11847267:C:T                                               AU3937301
4 chr1:13342921:T:C                                               AU1920301
5 chr1:13342933:G:T                                               AU1920301
6 chr1:13420931:C:T                                               AU1389305
7 chr1:23971953:C:A                                               AU4992303
  role    father_sampleID mother_sampleID gene
2 Sibling AU4690201       AU4690202       AGRN
3 Sibling AU3937201       AU3937202       NPPA
4 Sibling AU1920201       AU1920202       PRAMEF14
5 Sibling AU1920201       AU1920202       PRAMEF14
6 Sibling AU1389201       AU1389202       PRAMEF20
7 Sibling AU4992201       AU4992202       SRSF10
  consequence
2 ["splice_donor_variant","coding_sequence_variant","intron_variant"]
3 ["missense_variant"]
4 ["synonymous_variant"]
5 ["synonymous_variant"]
6 ["synonymous_variant"]
7 ["missense_variant"]
  hgvsc                                 isPTV isMIS isSYN isIndel
2 ENST00000379370.6:c.1177+4_1177+50del TRUE  FALSE FALSE TRUE
3 ENST00000376480.7:c.296G>A            FALSE TRUE  FALSE FALSE
4 ENST00000334600.6:c.1032A>G           FALSE FALSE TRUE  FALSE
5 ENST00000334600.6:c.1020C>A           FALSE FALSE TRUE  FALSE
6 ENST00000316412.9:c.1101C>T           FALSE FALSE TRUE  FALSE
7 ENST00000492112.2:c.334G>T            FALSE TRUE  FALSE FALSE
  gnomad_non_neuro_AF gnomad_non_neuro_AF_AFR MPC
2 0                   0                       .
3 1.46E-05            0                       0.023648
4 3.22E-05            0.00040783              .
5 8.19E-05            0.00011366              .
6 .                   .                       .
7 .                   .                       .

In [13]:
vars <- as.data.frame(unique(raw_vars[,c("variant")]))
colnames(vars) <- "variant"

In [22]:
head(vars)

  variant
1 chr1:11847267:C:T
2 chr1:13342921:T:C
3 chr1:13342933:G:T
4 chr1:13420931:C:T
5 chr1:23971953:C:A
6 chr1:27997351:C:A

In [14]:
vars

# Split the column into separate columns
split_data <- str_split(vars$variant, ":", simplify = TRUE)

# Rename the columns
colnames(split_data) <- c("chrom", "pos", "ref", "alt")

# Bind the split columns to the original dataframe
vars <- cbind(vars, split_data)

vars$pos <- as.numeric(vars$pos)

vars <- vars[!(vars$chrom == "chrX"),]
# remove x

vars$chr_num <- as.numeric(sub("^chr", "", vars$chrom))

    variant
1   chr1:1041678:CGCTCCGGCCAGTGCCAGGGTCGAGGTGAGCGGCTCCCCCGGGGGAGG:C
2   chr1:11847267:C:T
3   chr1:13342921:T:C
4   chr1:13342933:G:T
5   chr1:13420931:C:T
6   chr1:23971953:C:A
7   chr1:27997351:C:A
8   chr1:33479619:G:A
9   chr1:35832479:C:T
10  chr1:41513571:G:A
11  chr1:42842978:C:T
12  chr1:44828567:ATGT:A
13  chr1:45628347:G:C
14  chr1:55124491:A:C
15  chr1:57136584:T:A
16  chr1:62121248:A:C
17  chr1:77962930:C:T
18  chr1:93533069:G:GAC
19  chr1:93534908:G:GGGCCCAGCACTAGAAGATTTCAGTCATCTGCCACCAGAACAGAGAC
20  chr1:98684921:A:G
21  chr1:109171944:C:A
22  chr1:109264888:A:G
23  chr1:152155988:T:C
24  chr1:152155992:T:C
25  chr1:152156009:C:T
26  chr1:153760842:T:C
27  chr1:154331447:C:T
28  chr1:159873043:C:T
29  chr1:160231296:C:T
30  chr1:169827765:A:T
... ...
437 chr11:77900568:C:T
438 chr11:117428332:A:G
439 chr11:118371586:A:C
440 chr11:125606377:G:A
441 chr12:6121314:C:T
442 chr12:50353331:T:C
443 chr12:64467021:C:T
444 chr12:120560884:A:C
445 chr13:109785195:T:A
446 chr13:113076155:A:C
447 chr14:57594122:T:C
448 chr14:73198052:C:T
449 chr16:84179277:G:C
450 chr16:85690761:G:A
451 chr17:519293:C:A
452 chr17:37097103:CCAG:C
453 chr18:47100311:C:T
454 chr19:9251556:T:G
455 chr19:17235669:G:A
456 chr19:18134950:C:A
457 chr19:49744264:C:T
458 chr19:50414832:G:C
459 chr19:55593274:T:G
460 chr19:56033686:A:G
461 chr19:58262137:CA:C
462 chr21:39313305:G:A
463 chr21:45283435:G:A
464 chr22:30470065:C:T
465 chr22:50518159:G:A
466 chrX:15283554:T:C

In [24]:
head(as.numeric(sub("^chr", "", vars$chrom)
    ))

[1] 1 1 1 1 1 1

In [27]:
unique(vars$chr_num)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22

In [15]:
head(vars)

  variant                                                         chrom
1 chr1:1041678:CGCTCCGGCCAGTGCCAGGGTCGAGGTGAGCGGCTCCCCCGGGGGAGG:C chr1
2 chr1:11847267:C:T                                               chr1
3 chr1:13342921:T:C                                               chr1
4 chr1:13342933:G:T                                               chr1
5 chr1:13420931:C:T                                               chr1
6 chr1:23971953:C:A                                               chr1
  pos      ref                                              alt chr_num
1  1041678 CGCTCCGGCCAGTGCCAGGGTCGAGGTGAGCGGCTCCCCCGGGGGAGG C   1
2 11847267 C                                                T   1
3 13342921 T                                                C   1
4 13342933 G                                                T   1
5 13420931 C                                                T   1
6 23971953 C                                                A   1

In [36]:
msp <- 


var_msp

ERROR: Error in eval(expr, envir, enclos): object 'var_msp' not found

In [35]:
c(outer(unlist(var_indv[var_indv$variant == chr_vars$variant[1],]$sampleIDs), c(".0", ".1"), paste0))

[1] "AU4690305.0" "AU4690305.1"

In [60]:
find_regions <- function(chr_vars, msp){

# Initialize an empty dataframe to store the results
results_df <- data.frame(variant = character(), zeros = integer(), ones = integer(), stringsAsFactors = FALSE)

# Loop through each variant in chr_vars
for (i in seq_along(chr_vars$variant)) {
  # Subset var_msp for the corresponding position
  var_msp <- msp[msp$spos <= chr_vars$pos[i] & msp$epos >= chr_vars$pos[i], ]

  var_cols <- c(outer(unlist(var_indv[var_indv$variant == chr_vars$variant[i],]$sampleIDs), c(".0", ".1"), paste0))
  #print(var_cols)
  var_msp <- var_msp[,colnames(var_msp) %in% var_cols]
  #print(colnames(var_msp))  
    
 if(nrow(var_msp)>1){
    print(paste("Overlapping variant window:", chr_vars$variant[i]))
  }
  # Extract columns ending with .0
 # id_columns <- grep(paste0(chr_vars$variant[i], "\\.0$"), names(var_msp), value = TRUE)
  id_columns <- grep("\\.0$", names(var_msp), value = TRUE)
  # Initialize counters for zeros and ones
  num_zeros <- 0
  num_ones <- 0
  
  # Loop through each column and count zeros and ones
  for (col_name in id_columns) {
    # Get corresponding .1 column
    id_col_1 <- sub("\\.0$", ".1", col_name)
    
    # Count zeros and ones
    num_zeros <- num_zeros + sum(var_msp[[col_name]] == 0 & var_msp[[id_col_1]] == 0)
    num_ones <- num_ones + sum(var_msp[[col_name]] == 1 & var_msp[[id_col_1]] == 1)
  }
  
  # Append results to the dataframe
  results_df <- rbind(results_df, data.frame(variant = chr_vars$variant[i], zeros = num_zeros, ones = num_ones))
}
 return(results_df)
    }

In [18]:
msp_dir <- "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/"

for(chr in 1){
msp_path <- paste0(msp_dir, "chr", chr, ".msp.tsv")
print(msp_path)
}

[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr1.msp.tsv"

In [ ]:
"/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr1.msp.tsv"

In [61]:
start.time <- Sys.time()
total_results <- data.frame(variant = character(), zeros = integer(), ones = integer(), stringsAsFactors = FALSE)

msp_dir <- "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/"
#chr <- 1
for(chr in 1:22){
    print(paste("Starting Chromosome:", chr))
    msp_path <- paste0(msp_dir, "chr", chr, ".msp.tsv")

    # Read the first line of the file to extract column names
    col_names <- readLines(msp_path, n = 2)[2]
    col_names <- strsplit(col_names, "\t")[[1]]
    col_names[1] <- substring(col_names[1], 2)  # Remove the leading #

    # Read the .tsv file into R, skipping the first line
    msp <- read.table(msp_path, header = FALSE, sep = "\t", col.names = col_names)
    
    chr_vars <- vars[vars$chr_num == chr,]
    
    chr_result <- find_regions(chr_vars, msp)
    
    total_results <- rbind(total_results, chr_result)
}
end.time <- Sys.time()
time.taken <- round(end.time - start.time,2)
time.taken
# 2.9 minutes for ace
# 33.77 secs when filter by columns

[1] "Starting Chromosome: 1"
[1] "Starting Chromosome: 2"
[1] "Starting Chromosome: 3"
[1] "Starting Chromosome: 4"
[1] "Starting Chromosome: 5"
[1] "Starting Chromosome: 6"
[1] "Starting Chromosome: 7"
[1] "Starting Chromosome: 8"
[1] "Starting Chromosome: 9"
[1] "Starting Chromosome: 10"
[1] "Starting Chromosome: 11"
[1] "Starting Chromosome: 12"
[1] "Starting Chromosome: 13"
[1] "Starting Chromosome: 14"
[1] "Starting Chromosome: 15"
[1] "Starting Chromosome: 16"
[1] "Starting Chromosome: 17"
[1] "Starting Chromosome: 18"
[1] "Starting Chromosome: 19"
[1] "Starting Chromosome: 20"
[1] "Starting Chromosome: 21"
[1] "Starting Chromosome: 22"

Time difference of 33.77 secs

In [62]:
total_results

    variant
1   chr1:1041678:CGCTCCGGCCAGTGCCAGGGTCGAGGTGAGCGGCTCCCCCGGGGGAGG:C
2   chr1:11847267:C:T
3   chr1:13342921:T:C
4   chr1:13342933:G:T
5   chr1:13420931:C:T
6   chr1:23971953:C:A
7   chr1:27997351:C:A
8   chr1:33479619:G:A
9   chr1:35832479:C:T
10  chr1:41513571:G:A
11  chr1:42842978:C:T
12  chr1:44828567:ATGT:A
13  chr1:45628347:G:C
14  chr1:55124491:A:C
15  chr1:57136584:T:A
16  chr1:62121248:A:C
17  chr1:77962930:C:T
18  chr1:93533069:G:GAC
19  chr1:93534908:G:GGGCCCAGCACTAGAAGATTTCAGTCATCTGCCACCAGAACAGAGAC
20  chr1:98684921:A:G
21  chr1:109171944:C:A
22  chr1:109264888:A:G
23  chr1:152155988:T:C
24  chr1:152155992:T:C
25  chr1:152156009:C:T
26  chr1:153760842:T:C
27  chr1:154331447:C:T
28  chr1:159873043:C:T
29  chr1:160231296:C:T
30  chr1:169827765:A:T
... ...
436 chr20:50892784:G:A
437 chr20:62813386:A:AGGGATGAGCCAGCCGAGAGCCCATCGGAGACCCCAGGCCCCCGCCCAGCAGGACCTGCAG
438 chr20:62813443:G:A
439 chr20:62813446:G:A
440 chr21:18260197:C:T
441 chr21:29555290:C:G
442 chr21:33555174:CAGCCGCCGGAGCCGCACCCCT:C
443 chr21:44528461:C:T
444 chr21:44697327:C:T
445 chr21:46648488:C:CCA
446 chr21:39313305:G:A
447 chr21:45283435:G:A
448 chr22:21675112:G:A
449 chr22:22031439:A:C
450 chr22:22162672:G:T
451 chr22:22202129:T:A
452 chr22:22369836:G:C
453 chr22:22734871:A:G
454 chr22:22735048:G:T
455 chr22:22819619:G:A
456 chr22:22871796:C:T
457 chr22:22881257:T:G
458 chr22:22881389:T:C
459 chr22:26464479:G:T
460 chr22:39080950:G:A
461 chr22:42693744:GT:G
462 chr22:44496838:TA:T
463 chr22:50050103:C:T
464 chr22:30470065:C:T
465 chr22:50518159:G:A
    zeros ones
1   0     0
2   0     1
3   0     0
4   0     0
5   0     1
6   0     0
7   2     0
8   0     0
9   0     1
10  0     1
11  0     0
12  0     1
13  0     0
14  0     1
15  0     1
16  0     1
17  0     1
18  0     0
19  0     0
20  1     0
21  0     1
22  0     1
23  0     0
24  0     0
25  0     0
26  0     1
27  1     0
28  0     0
29  1     0
30  0     1
... ...   ...
436 0     0
437 0     1
438 0     0
439 0     0
440 0     0
441 0     1
442 0     0
443 0     1
444 0     1
445 0     0
446 0     0
447 0     0
448 0     1
449 0     0
450 0     0
451 0     0
452 0     0
453 0     0
454 0     0
455 0     1
456 0     0
457 0     1
458 0     1
459 0     1
460 0     0
461 0     0
462 0     1
463 0     0
464 0     0
465 0     0

In [63]:
dim(total_results)

[1] 465   3

In [64]:
range(total_results$zeros + total_results$ones)
#2612 individuals

[1] 0 2

In [65]:
range(total_results$zeros)

[1] 0 2

In [40]:
range(total_results$ones)

[1]    0 1072

In [35]:
dim(vars)

[1] 470  32

In [41]:
write.csv(total_results, "ace_pilot_rare_vars.csv")

In [66]:
sum(total_results$ones)

[1] 216

In [43]:
sum(total_results$zeros)
#ceu= eur

[1] 650586

In [44]:
sum(total_results$ones)/(sum(total_results$ones)+sum(total_results$zeros))

[1] 0.3828751