In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
#vars of interest
raw_vars <- read.table('ACE_autosomal_gnomAD_filtered_HQ_rare_CNVs_table_Children_included_in_analysis_v2024-04-29_sharing_2024-06-14.txt', sep = "\t")

# Make the first row as column names
colnames(raw_vars) <- raw_vars[1, ]

# Remove the first row
raw_vars <- raw_vars[-1, ]

#raw_vars$sampleID <- paste0(raw_vars$sampleID, "_", raw_vars$sampleID)

In [3]:
colnames(raw_vars) <- c("chr", "start", "end", "svtype", "copy_number", "sampleID")

In [4]:
head(raw_vars)

  chr  start     end       svtype copy_number sampleID
2 chr6 167324974 167348151 DEL    1           AU3303303
3 chr1 11037596  11045765  DEL    1           AU4122301
4 chr1 1455363   1462806   DEL    1           AU3853302
5 chr6 49470062  49472956  DUP    3           AU3853302
6 chr7 5359301   5390726   DUP    3           AU3853302
7 chr7 5716619   6024899   DUP    3           AU3853302

In [4]:
raw_vars$change <- paste(raw_vars$chr, raw_vars$start, raw_vars$end, sep = ":")

In [5]:
raw_vars$chr <- as.numeric(gsub("chr", "", raw_vars$chr))

In [7]:
head(raw_vars)

  chr start     end       svtype copy_number sampleID  change
2 6   167324974 167348151 DEL    1           AU3303303 chr6:167324974:167348151
3 1   11037596  11045765  DEL    1           AU4122301 chr1:11037596:11045765
4 1   1455363   1462806   DEL    1           AU3853302 chr1:1455363:1462806
5 6   49470062  49472956  DUP    3           AU3853302 chr6:49470062:49472956
6 7   5359301   5390726   DUP    3           AU3853302 chr7:5359301:5390726
7 7   5716619   6024899   DUP    3           AU3853302 chr7:5716619:6024899

In [6]:
var_indv <- raw_vars %>%
  group_by(change) %>%
  summarize(sampleIDs = list(unique(sampleID)))

In [7]:
head(var_indv)

  change                    sampleIDs
1 chr10:113583119:113731005 AU4935301
2 chr10:122488805:122566094 DG1015-302
3 chr10:122585174:122590792 AU1324303
4 chr10:122585174:122598110 DG1076-301
5 chr10:122597877:122600191 AU4946302, AU4784303
6 chr10:122832061:122850648 DG1069-301

In [8]:
dim(var_indv)

[1] 643   2

In [9]:
typeof(var_indv$sampleIDs)

[1] "list"

In [10]:
lengths_table <- sapply(var_indv$sampleIDs, length)

In [11]:
head(lengths_table)

[1] 1 1 1 1 2 1

In [10]:
table(lengths_table)

lengths_table
  1   2   3   4   5   6   7   9  11
465 117  30  13  10   5   1   1   1

In [12]:
var_info <- unique(raw_vars[,c("chr", "start", "end", "change")])

In [17]:
dim(var_info)

[1] 643   4

In [13]:
var_indv <- left_join(var_indv, var_info)

Joining with `by = join_by(change)`

In [19]:
dim(var_indv)

[1] 643   5

In [15]:
head(var_indv)

  change                    sampleIDs            chr start     end
1 chr10:113583119:113731005 AU4935301            10  113583119 113731005
2 chr10:122488805:122566094 DG1015-302           10  122488805 122566094
3 chr10:122585174:122590792 AU1324303            10  122585174 122590792
4 chr10:122585174:122598110 DG1076-301           10  122585174 122598110
5 chr10:122597877:122600191 AU4946302, AU4784303 10  122597877 122600191
6 chr10:122832061:122850648 DG1069-301           10  122832061 122850648

In [14]:
var_indv$start <- as.numeric(var_indv$start)

var_indv$end <- as.numeric(var_indv$end)

In [17]:
c(outer(unlist(var_indv$sampleIDs[5]), c(".0", ".1"), paste0))

[1] "AU4946302.0" "AU4784303.0" "AU4946302.1" "AU4784303.1"

In [23]:
table(var_indv$chr)

 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
73 49 34 28 27 22 32 27 29 29 35 31  7 12 31 35 25  9 61 18  6 23

In [15]:
for(chr in 1:22){
    print(dim(var_indv[var_indv$chr == chr,]))
    }

[1] 73  5
[1] 49  5
[1] 34  5
[1] 28  5
[1] 27  5
[1] 22  5
[1] 32  5
[1] 27  5
[1] 29  5
[1] 29  5
[1] 35  5
[1] 31  5
[1] 7 5
[1] 12  5
[1] 31  5
[1] 35  5
[1] 25  5
[1] 9 5
[1] 61  5
[1] 18  5
[1] 6 5
[1] 23  5

In [59]:
msp_test_path <-  "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/rfmix_out/chr2.msp.tsv"
col_names <- readLines(msp_test_path, n = 2)[2]
col_names <- strsplit(col_names, "\t")[[1]]
col_names[1] <- substring(col_names[1], 2)

In [60]:
test_msp <- read.table(msp_test_path, header = FALSE, sep = "\t", col.names = col_names)

In [61]:
dim(test_msp)

[1] 2001 5230

In [29]:
head(test_msp)

  chm spos   epos   sgpos egpos n.snps AU003305.0 AU003305.1 AU0226302.0
1 2    15703 320574 0.00  0.24  132    0          0          0
2 2   320574 384236 0.24  0.43   20    0          0          0
3 2   384236 502023 0.43  0.70   40    0          0          0
4 2   502023 596532 0.70  0.75   40    0          0          0
5 2   596532 654472 0.75  0.86   50    0          0          0
6 2   654472 664719 0.86  0.93   10    0          0          0
  AU0226302.1 ⋯ DG1580.201.0 DG1580.201.1 DG1580.202.0 DG1580.202.1
1 0           ⋯ 0            1            0            0
2 0           ⋯ 0            1            0            0
3 0           ⋯ 0            1            0            0
4 0           ⋯ 0            1            0            0
5 0           ⋯ 0            1            0            0
6 0           ⋯ 0            1            0            0
  DG1580.301.0 DG1580.301.1 DG1228.202.0 DG1228.202.1 DG1228.302.0 DG1228.302.1
1 1            0            1            1            1            1
2 1            0            1            1            1            1
3 1            0            1            1            1            1
4 1            0            1            1            1            1
5 1            0            1            1            1            1
6 1            0            1            1            1            1

In [36]:
# doesnt return all indv
find_regions <- function(chr_vars, msp){

# Initialize an empty dataframe to store the results
results_df <- data.frame(change = character(), zeros = integer(), 
                         ones = integer(), zero_ids = I(list()), one_ids = I(list()), 
                         stringsAsFactors = FALSE)
# Loop through each variant in chr_vars
for (i in seq_along(chr_vars$change)) {
  # Subset var_msp for the corresponding position
#i <- 6
  var_msp <- msp[msp$spos <= chr_vars$start[i] & msp$epos >= chr_vars$end[i], ]
    #print(var_msp[,1:4])
    #print(paste(chr_vars$start[i], chr_vars$end[i], sep = ": "))
  var_cols <- c(outer(unlist(chr_vars$sampleIDs[i]), c(".0", ".1"), paste0))
  #print(var_cols)
  var_msp <- var_msp[,colnames(var_msp) %in% var_cols]
  #print(colnames(var_msp))  
 if(nrow(var_msp)>1){
    print(paste("Overlapping Variant Window:", chr_vars$change[i]))}
     
 if(nrow(var_msp)==1){
    print(paste("Hit:", chr_vars$change[i]))
  
  # Extract columns ending with .0
 # id_columns <- grep(paste0(chr_vars$variant[i], "\\.0$"), names(var_msp), value = TRUE)
  id_columns <- grep("\\.0$", names(var_msp), value = TRUE)
  # Initialize counters for zeros and ones
  num_zeros <- 0
  num_ones <- 0
  zero_indv <- list()
  one_indv <- list()
      # Loop through each column and count zeros and ones
  for (col_name in id_columns) {
    # Get corresponding .1 column
    id_col_1 <- sub("\\.0$", ".1", col_name)
    
      print(var_msp)
    print(paste(col_name, var_msp[[col_name]], var_msp[[id_col_1]], sep = ": "))
  
    # Count zeros and ones
    if(var_msp[[col_name]] == 0 & var_msp[[id_col_1]] == 0){
        zero_indv <- c(zero_indv, list(sub("\\.0$", "", col_name)))
        num_zeros <- num_zeros + 1
    }
    if(var_msp[[col_name]] == 1 & var_msp[[id_col_1]] == 1){
        one_indv <- c(one_indv, list(sub("\\.0$", "", col_name)))
        num_ones <- num_ones + 1
    }
  }
  if(length(zero_indv)<1){
        zero_indv <- NA
  }
    if(length(one_indv)<1){
            one_indv <- NA
    }
 
  # Append results to the dataframe
  results_df <- rbind(results_df, data.frame(change = chr_vars$change[i], 
                                             zeros = num_zeros, ones = num_ones, 
                                             zero_ids = paste(unlist(zero_indv), sep=", "), 
                                             one_ids = paste(unlist(one_indv),sep=", ")))
 }
 
}
 return(results_df)
    }

In [63]:
find_regions <- function(chr_vars, msp) {

  # Initialize an empty dataframe to store the results
  results_df <- data.frame(change = character(), zeros = integer(), 
                           ones = integer(), zero_ids = I(list()), one_ids = I(list()), 
                           stringsAsFactors = FALSE)
  
  # Loop through each variant in chr_vars
  for (i in seq_along(chr_vars$change)) {
    # Subset var_msp for the corresponding position
    var_msp <- msp[msp$spos <= chr_vars$start[i] & msp$epos >= chr_vars$end[i], ]
    var_cols <- c(outer(unlist(chr_vars$sampleIDs[i]), c(".0", ".1"), paste0))
    var_msp <- var_msp[, colnames(var_msp) %in% var_cols]
    
    if (nrow(var_msp) > 1) {
      print(paste("Overlapping Variant Window:", chr_vars$change[i]))
    }
    
    if (nrow(var_msp) == 1) {
      print(paste("Hit:", chr_vars$change[i]))
      
      # Extract columns ending with .0
      id_columns <- grep("\\.0$", names(var_msp), value = TRUE)
      
      # Initialize counters for zeros and ones
      num_zeros <- 0
      num_ones <- 0
      zero_indv <- c()
      one_indv <- c()
      
      # Loop through each column and count zeros and ones
      for (col_name in id_columns) {
        # Get corresponding .1 column
        id_col_1 <- sub("\\.0$", ".1", col_name)
        
        # Count zeros and ones
        if (var_msp[[col_name]] == 0 & var_msp[[id_col_1]] == 0) {
          zero_indv <- c(zero_indv, sub("\\.0$", "", col_name))
          num_zeros <- num_zeros + 1
        }
        if (var_msp[[col_name]] == 1 & var_msp[[id_col_1]] == 1) {
          one_indv <- c(one_indv, sub("\\.0$", "", col_name))
          num_ones <- num_ones + 1
        }
      }
      
      if (length(zero_indv) < 1) {
        zero_indv <- NA
      }
      if (length(one_indv) < 1) {
        one_indv <- NA
      }
      
      # Append results to the dataframe
      results_df <- rbind(results_df, data.frame(
        change = chr_vars$change[i], 
        zeros = num_zeros, ones = num_ones, 
        zero_ids = I(list(zero_indv)), 
        one_ids = I(list(one_indv))
      ))
    }
  }
  return(results_df)
}

In [64]:
start.time <- Sys.time()
total_results <- data.frame(variant = character(), zeros = integer(), 
                         ones = integer(), zero_ids = I(list()), one_ids = I(list()), 
                         stringsAsFactors = FALSE)

msp_dir <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/rfmix_out/"
#chr <- 1
for(chr in 1:22){
    print(paste("Starting Chromosome:", chr))
    msp_path <- paste0(msp_dir, "chr", chr, ".msp.tsv")

    # Read the first line of the file to extract column names
    col_names <- readLines(msp_path, n = 2)[2]
    col_names <- strsplit(col_names, "\t")[[1]]
    col_names[1] <- substring(col_names[1], 2)  # Remove the leading #

    # Read the .tsv file into R, skipping the first line
    msp <- read.table(msp_path, header = FALSE, sep = "\t", col.names = col_names)
    
    chr_vars <- var_indv[var_indv$chr == chr,]
    
    chr_result <- find_regions(chr_vars, msp)
    
    total_results <- rbind(total_results, chr_result)
}
end.time <- Sys.time()
time.taken <- round(end.time - start.time,2)
time.taken

[1] "Starting Chromosome: 1"
[1] "Hit: chr1:103525603:103552876"
[1] "Hit: chr1:109235113:109238280"
[1] "Hit: chr1:109279459:109281327"
[1] "Hit: chr1:11029562:11045765"
[1] "Hit: chr1:11037596:11045765"
[1] "Hit: chr1:12755603:12776216"
[1] "Hit: chr1:12755603:12778004"
[1] "Hit: chr1:1455363:1462806"
[1] "Hit: chr1:1457032:1462806"
[1] "Hit: chr1:145730647:145789064"
[1] "Hit: chr1:153816176:153819833"
[1] "Hit: chr1:154947597:154948499"
[1] "Hit: chr1:155728945:155732299"
[1] "Hit: chr1:156339537:156347093"
[1] "Hit: chr1:160879214:160881619"
[1] "Hit: chr1:160948554:160952831"
[1] "Hit: chr1:168225841:168243309"
[1] "Hit: chr1:168231417:168236868"
[1] "Hit: chr1:169230617:169324598"
[1] "Hit: chr1:173533512:173858425"
[1] "Hit: chr1:186353591:186449581"
[1] "Hit: chr1:19201621:19260226"
[1] "Hit: chr1:196331059:196342347"
[1] "Hit: chr1:196993983:197004941"
[1] "Hit: chr1:197902533:197913278"
[1] "Hit: chr1:202434559:202440886"
[1] "Hit: chr1:206009167:206023993"
[1] "Hit: chr1:207581821:207645428"
[1] "Hit: chr1:214652731:214664669"
[1] "Hit: chr1:215837894:215846131"
[1] "Hit: chr1:216173849:216200219"
[1] "Hit: chr1:225257863:225265467"
[1] "Hit: chr1:225364695:225406930"
[1] "Hit: chr1:225860561:225863192"
[1] "Hit: chr1:231335263:231340159"
[1] "Hit: chr1:231370143:231422385"
[1] "Hit: chr1:24595327:24606536"
[1] "Hit: chr1:248203857:248408118"
[1] "Hit: chr1:25231373:25361606"
[1] "Hit: chr1:28205161:28238203"
[1] "Hit: chr1:28683467:28738436"
[1] "Hit: chr1:3477778:3481211"
[1] "Hit: chr1:3492542:3499364"
[1] "Hit: chr1:35111675:35115957"
[1] "Hit: chr1:44783488:44785774"
[1] "Hit: chr1:60025304:60041229"
[1] "Hit: chr1:84144174:84197922"
[1] "Hit: chr1:8945770:8959100"
[1] "Hit: chr1:923831:1087734"
[1] "Hit: chr1:923831:1091323"
[1] "Hit: chr1:93524164:93535006"
[1] "Hit: chr1:93529555:93535006"
[1] "Starting Chromosome: 2"
[1] "Hit: chr2:110115591:110212973"
[1] "Hit: chr2:111940205:112029659"
[1] "Hit: chr2:120127591:120294808"
[1] "Hit: chr2:127279076:127324339"
[1] "Hit: chr2:130313837:130375503"
[1] "Hit: chr2:130330045:130375503"
[1] "Hit: chr2:147917186:147948322"
[1] "Hit: chr2:147972642:147976073"
[1] "Hit: chr2:189441349:189488090"
[1] "Hit: chr2:189741245:189755658"
[1] "Hit: chr2:199935834:199940231"
[1] "Hit: chr2:206745525:206749281"
[1] "Hit: chr2:217803770:217831645"
[1] "Hit: chr2:218124:243660"
[1] "Hit: chr2:227080346:227147682"
[1] "Hit: chr2:227472035:227525013"
[1] "Hit: chr2:23958204:24000544"
[1] "Hit: chr2:240716497:240769804"
[1] "Hit: chr2:241735020:241744975"
[1] "Hit: chr2:26516321:26562784"
[1] "Hit: chr2:27439669:27455521"
[1] "Hit: chr2:28495963:28529877"
[1] "Hit: chr2:28495963:28532292"
[1] "Hit: chr2:33549507:33563739"
[1] "Hit: chr2:36551959:36560963"
[1] "Hit: chr2:36551959:36583567"
[1] "Hit: chr2:36551959:36598289"
[1] "Hit: chr2:38295714:38319117"
[1] "Hit: chr2:44299874:44315341"
[1] "Hit: chr2:44319328:44323509"
[1] "Hit: chr2:47369275:47380067"
[1] "Hit: chr2:55683688:55687803"
[1] "Hit: chr2:65253631:65265273"
[1] "Hit: chr2:668850:677571"
[1] "Hit: chr2:75646686:75666151"
[1] "Hit: chr2:85389451:85402256"
[1] "Hit: chr2:97348802:97659989"
[1] "Starting Chromosome: 3"
[1] "Hit: chr3:10164822:10226531"
[1] "Hit: chr3:108642341:108651260"
[1] "Hit: chr3:109327085:109332288"
[1] "Hit: chr3:109328793:109334091"
[1] "Hit: chr3:112532413:112562371"
[1] "Hit: chr3:113723325:113746398"
[1] "Hit: chr3:113869410:113901244"
[1] "Hit: chr3:129030352:129034427"
[1] "Hit: chr3:129252184:129257958"
[1] "Hit: chr3:132558041:132561315"
[1] "Hit: chr3:134207375:134222637"
[1] "Hit: chr3:143050842:143057194"
[1] "Hit: chr3:14496320:14574890"
[1] "Hit: chr3:155762520:155775946"
[1] "Hit: chr3:165058866:165060125"
[1] "Hit: chr3:177025888:177065120"
[1] "Hit: chr3:197043647:197066852"
[1] "Hit: chr3:41907748:41978132"
[1] "Hit: chr3:47568974:47622439"
[1] "Hit: chr3:52687445:52689226"
[1] "Hit: chr3:94049309:94064644"
[1] "Starting Chromosome: 4"
[1] "Hit: chr4:106170998:106309087"
[1] "Hit: chr4:119135687:119195700"
[1] "Hit: chr4:119135687:119195939"
[1] "Hit: chr4:119136415:119186877"
[1] "Hit: chr4:120059359:120067099"
[1] "Hit: chr4:13460602:13484463"
[1] "Hit: chr4:175633998:175641843"
[1] "Hit: chr4:6277354:6292095"
[1] "Hit: chr4:68234366:68241902"
[1] "Hit: chr4:74036492:74086770"
[1] "Hit: chr4:77047058:77066503"
[1] "Hit: chr4:78281301:78286637"
[1] "Hit: chr4:85634:205107"
[1] "Hit: chr4:88113206:88140112"
[1] "Hit: chr4:97943800:98134557"
[1] "Hit: chr4:97943800:98143574"
[1] "Starting Chromosome: 5"
[1] "Hit: chr5:1008705:1039041"
[1] "Hit: chr5:110738625:110762193"
[1] "Hit: chr5:111091619:111111650"
[1] "Hit: chr5:141933162:141939402"
[1] "Hit: chr5:172641166:172687490"
[1] "Hit: chr5:172656425:172687490"
[1] "Hit: chr5:177992138:177996340"
[1] "Hit: chr5:180988749:181050467"
[1] "Hit: chr5:180992716:181050467"
[1] "Hit: chr5:32125678:32143978"
[1] "Hit: chr5:612055:666221"
[1] "Hit: chr5:624374:678162"
[1] "Hit: chr5:69299915:69334347"
[1] "Hit: chr5:75593781:75598348"
[1] "Hit: chr5:863644:876310"
[1] "Hit: chr5:96780961:96784178"
[1] "Starting Chromosome: 6"
[1] "Hit: chr6:116236869:116239221"
[1] "Hit: chr6:117308697:117311215"
[1] "Hit: chr6:135429785:135433354"
[1] "Hit: chr6:167324974:167348151"
[1] "Hit: chr6:169216962:169250904"
[1] "Hit: chr6:170404082:170537438"
[1] "Hit: chr6:35509112:35512994"
[1] "Hit: chr6:35509112:35597502"
[1] "Hit: chr6:35555776:35608032"
[1] "Hit: chr6:35574766:35608032"
[1] "Hit: chr6:35765811:35781307"
[1] "Hit: chr6:49463006:49472956"
[1] "Hit: chr6:49470062:49472956"
[1] "Hit: chr6:64902016:64912841"
[1] "Hit: chr6:73322740:73364269"
[1] "Hit: chr6:75601412:75716350"
[1] "Starting Chromosome: 7"
[1] "Hit: chr7:100722913:100738711"
[1] "Hit: chr7:102464617:102473782"
[1] "Hit: chr7:122098353:122162341"
[1] "Hit: chr7:140568666:140602640"
[1] "Hit: chr7:142771952:142788645"
[1] "Hit: chr7:143131980:143139837"
[1] "Hit: chr7:143131980:143184533"
[1] "Hit: chr7:143875892:144158059"
[1] "Hit: chr7:150856358:150861602"
[1] "Hit: chr7:15390574:15394277"
[1] "Hit: chr7:16375995:16421636"
[1] "Hit: chr7:20405965:20410714"
[1] "Hit: chr7:2229887:2278403"
[1] "Hit: chr7:2234098:2278403"
[1] "Hit: chr7:5359301:5390726"
[1] "Hit: chr7:66633178:66641545"
[1] "Hit: chr7:71665314:71713698"
[1] "Hit: chr7:7357535:7381710"
[1] "Hit: chr7:76054407:76060596"
[1] "Hit: chr7:99029935:99036575"
[1] "Hit: chr7:99604289:99607908"
[1] "Starting Chromosome: 8"
[1] "Hit: chr8:108214510:108228489"
[1] "Hit: chr8:144360760:144401773"
[1] "Hit: chr8:22080083:22082625"
[1] "Hit: chr8:240205:247440"
[1] "Hit: chr8:27536687:27540754"
[1] "Hit: chr8:30062906:30083565"
[1] "Hit: chr8:39922455:39925469"
[1] "Hit: chr8:47279765:47294526"
[1] "Hit: chr8:52538334:52565528"
[1] "Hit: chr8:6405309:6477729"
[1] "Hit: chr8:66767303:66881072"
[1] "Hit: chr8:96231589:96235792"
[1] "Starting Chromosome: 9"
[1] "Hit: chr9:104095202:104140278"
[1] "Hit: chr9:112645553:112716639"
[1] "Hit: chr9:112645553:112817913"
[1] "Hit: chr9:112659166:112817913"
[1] "Hit: chr9:128257327:128267615"
[1] "Hit: chr9:133470997:133479225"
[1] "Hit: chr9:135561659:135564452"
[1] "Hit: chr9:136802567:136815634"
[1] "Hit: chr9:213849:399357"
[1] "Hit: chr9:24542855:24546227"
[1] "Hit: chr9:35662849:35664590"
[1] "Hit: chr9:35696851:35708582"
[1] "Hit: chr9:5122907:5128281"
[1] "Hit: chr9:5163771:5234479"
[1] "Hit: chr9:72816046:72837120"
[1] "Hit: chr9:76188481:76194120"
[1] "Hit: chr9:89318403:89338678"
[1] "Hit: chr9:89319555:89359761"
[1] "Hit: chr9:92031049:92050165"
[1] "Hit: chr9:96640734:96651810"
[1] "Starting Chromosome: 10"
[1] "Hit: chr10:122585174:122590792"
[1] "Hit: chr10:122585174:122598110"
[1] "Hit: chr10:122597877:122600191"
[1] "Hit: chr10:13233441:13234472"
[1] "Hit: chr10:133325665:133328113"
[1] "Hit: chr10:133526162:133533995"
[1] "Hit: chr10:133527982:133533995"
[1] "Hit: chr10:133536966:133609111"
[1] "Hit: chr10:14945008:14972955"
[1] "Hit: chr10:32543203:32584402"
[1] "Hit: chr10:35178775:35201584"
[1] "Hit: chr10:42796377:42802316"
[1] "Hit: chr10:73539347:73541990"
[1] "Hit: chr10:80336008:80352825"
[1] "Hit: chr10:84194440:84196748"
[1] "Hit: chr10:84194440:84197934"
[1] "Hit: chr10:91935055:92145210"
[1] "Hit: chr10:95314290:95341776"
[1] "Starting Chromosome: 11"
[1] "Hit: chr11:111860450:111889572"
[1] "Hit: chr11:112199602:112236132"
[1] "Hit: chr11:113797777:113805144"
[1] "Hit: chr11:113797777:113831074"
[1] "Hit: chr11:113808219:113827458"
[1] "Hit: chr11:113823508:113831074"
[1] "Hit: chr11:113829100:113852731"
[1] "Hit: chr11:113831823:113852731"
[1] "Hit: chr11:113831823:113854433"
[1] "Hit: chr11:117178639:117182904"
[1] "Hit: chr11:14858946:14880866"
[1] "Hit: chr11:22374658:22378454"
[1] "Hit: chr11:32583701:32601920"
[1] "Hit: chr11:32583701:32603049"
[1] "Hit: chr11:44929974:44938515"
[1] "Hit: chr11:61481685:61487338"
[1] "Hit: chr11:62356228:62389924"
[1] "Hit: chr11:73872570:73900518"
[1] "Hit: chr11:85718138:85758212"
[1] "Hit: chr11:85718693:85758212"
[1] "Hit: chr11:85915322:85920119"
[1] "Hit: chr11:93408134:93438585"
[1] "Hit: chr11:94829953:94850357"
[1] "Starting Chromosome: 12"
[1] "Hit: chr12:113276821:113321446"
[1] "Hit: chr12:122263475:122274930"
[1] "Hit: chr12:122604467:122605513"
[1] "Hit: chr12:132489454:132525921"
[1] "Hit: chr12:138170:157792"
[1] "Hit: chr12:306797:412076"
[1] "Hit: chr12:49295050:49297824"
[1] "Hit: chr12:49295050:49298784"
[1] "Hit: chr12:50809359:50821260"
[1] "Hit: chr12:53049799:53068402"
[1] "Hit: chr12:53169974:53174042"
[1] "Hit: chr12:56951334:56958261"
[1] "Hit: chr12:63779745:63809660"
[1] "Hit: chr12:6883607:6919861"
[1] "Hit: chr12:7317040:7320902"
[1] "Hit: chr12:7765119:7770616"
[1] "Hit: chr12:7769886:7774219"
[1] "Hit: chr12:7922724:7936285"
[1] "Hit: chr12:9898576:9971785"
[1] "Hit: chr12:99049:162163"
[1] "Starting Chromosome: 13"
[1] "Hit: chr13:32740983:32776017"
[1] "Hit: chr13:52083163:52102052"
[1] "Starting Chromosome: 14"
[1] "Hit: chr14:104868327:104884647"
[1] "Hit: chr14:24209486:24210959"
[1] "Hit: chr14:34515841:34529573"
[1] "Hit: chr14:55158425:55189278"
[1] "Hit: chr14:64549823:64552986"
[1] "Hit: chr14:64766302:64780029"
[1] "Hit: chr14:70372305:70417188"
[1] "Hit: chr14:76153549:76172117"
[1] "Hit: chr14:91704455:91729577"
[1] "Hit: chr14:91936850:92025518"
[1] "Starting Chromosome: 15"
[1] "Hit: chr15:28110943:28192249"
[1] "Hit: chr15:32030365:32112461"
[1] "Hit: chr15:32684319:32697196"
[1] "Hit: chr15:41476349:41481574"
[1] "Hit: chr15:41557209:41573913"
[1] "Hit: chr15:41561030:41578228"
[1] "Hit: chr15:41567263:41578228"
[1] "Hit: chr15:42872514:42984091"
[1] "Hit: chr15:43834964:43839826"
[1] "Hit: chr15:44956590:44974053"
[1] "Hit: chr15:52049896:52061598"
[1] "Hit: chr15:55828976:55860876"
[1] "Hit: chr15:56388375:56391516"
[1] "Hit: chr15:56631154:56667084"
[1] "Hit: chr15:64815535:64824452"
[1] "Hit: chr15:68054082:68218748"
[1] "Hit: chr15:78616927:78630043"
[1] "Hit: chr15:84918427:84945896"
[1] "Hit: chr15:89908183:89913050"
[1] "Starting Chromosome: 16"
[1] "Hit: chr16:15879707:15888723"
[1] "Hit: chr16:27790485:27829054"
[1] "Hit: chr16:28813883:28990881"
[1] "Hit: chr16:30472622:30475678"
[1] "Hit: chr16:31416116:31428744"
[1] "Hit: chr16:3654165:3666216"
[1] "Hit: chr16:46498008:46618470"
[1] "Hit: chr16:57462460:57471895"
[1] "Hit: chr16:69339926:69343177"
[1] "Hit: chr16:75539319:75542781"
[1] "Hit: chr16:76535448:76559066"
[1] "Hit: chr16:77431198:77435131"
[1] "Hit: chr16:89845225:89858605"
[1] "Starting Chromosome: 17"
[1] "Hit: chr17:10340053:10364642"
[1] "Hit: chr17:10501549:10502959"
[1] "Hit: chr17:10504713:10529785"
[1] "Hit: chr17:10529123:10529785"
[1] "Hit: chr17:31851774:31901806"
[1] "Hit: chr17:39160384:39165932"
[1] "Hit: chr17:39742155:39743710"
[1] "Hit: chr17:39742155:39744490"
[1] "Hit: chr17:39870597:39873224"
[1] "Hit: chr17:41363401:41369911"
[1] "Hit: chr17:43006628:43015577"
[1] "Hit: chr17:47361281:47441410"
[1] "Hit: chr17:48111852:48113661"
[1] "Hit: chr17:50134563:50136295"
[1] "Hit: chr17:58593458:58630652"
[1] "Hit: chr17:59193395:59215345"
[1] "Hit: chr17:74946564:74953749"
[1] "Hit: chr17:7626137:7628249"
[1] "Hit: chr17:82957084:82965844"
[1] "Starting Chromosome: 18"
[1] "Hit: chr18:12672528:12680926"
[1] "Hit: chr18:41993173:41996828"
[1] "Hit: chr18:45825578:45843099"
[1] "Hit: chr18:58350894:58397062"
[1] "Hit: chr18:80034249:80046586"
[1] "Starting Chromosome: 19"
[1] "Hit: chr19:10378117:10393884"
[1] "Hit: chr19:12643178:12649526"
[1] "Hit: chr19:14028051:14042887"
[1] "Hit: chr19:15622717:15624192"
[1] "Hit: chr19:15683396:15697272"
[1] "Hit: chr19:16148627:16198406"
[1] "Hit: chr19:16482353:16506872"
[1] "Hit: chr19:18340501:18370048"
[1] "Hit: chr19:19914637:19935673"
[1] "Hit: chr19:19914637:19957114"
[1] "Hit: chr19:22072712:22089728"
[1] "Hit: chr19:22072712:22090604"
[1] "Hit: chr19:22072712:22130321"
[1] "Hit: chr19:23742699:23758989"
[1] "Hit: chr19:3110052:3121992"
[1] "Hit: chr19:3113233:3121992"
[1] "Hit: chr19:3114847:3121992"
[1] "Hit: chr19:36065861:36073589"
[1] "Hit: chr19:38948470:38950434"
[1] "Hit: chr19:3902390:3925457"
[1] "Hit: chr19:3933361:3942514"
[1] "Hit: chr19:41683688:41688465"
[1] "Hit: chr19:44516849:44525342"
[1] "Hit: chr19:4522434:4529964"
[1] "Hit: chr19:48883657:48888359"
[1] "Hit: chr19:49132904:49172206"
[1] "Hit: chr19:49165944:49172206"
[1] "Hit: chr19:50413329:50420071"
[1] "Hit: chr19:50997654:51001273"
[1] "Hit: chr19:53107782:53122841"
[1] "Hit: chr19:54724382:54806342"
[1] "Hit: chr19:55013608:55048861"
[1] "Hit: chr19:55360596:55361532"
[1] "Hit: chr19:56207937:56225527"
[1] "Hit: chr19:56413862:56442845"
[1] "Hit: chr19:58453599:58456949"
[1] "Hit: chr19:58498236:58514408"
[1] "Hit: chr19:6374714:6387657"
[1] "Hit: chr19:6375663:6387657"
[1] "Hit: chr19:7074899:7076605"
[1] "Hit: chr19:7074899:7084574"
[1] "Starting Chromosome: 20"
[1] "Hit: chr20:142493:159261"
[1] "Hit: chr20:31257567:31406313"
[1] "Hit: chr20:38334333:38337603"
[1] "Hit: chr20:45722250:45725928"
[1] "Hit: chr20:45722250:45746385"
[1] "Hit: chr20:46349256:46372067"
[1] "Hit: chr20:49251430:49299698"
[1] "Hit: chr20:49539473:49550287"
[1] "Hit: chr20:58309618:58360483"
[1] "Hit: chr20:63346010:63361494"
[1] "Hit: chr20:8727212:8737290"
[1] "Starting Chromosome: 21"
[1] "Hit: chr21:14143412:14189517"
[1] "Hit: chr21:18352806:18403883"
[1] "Hit: chr21:30541438:30643234"
[1] "Hit: chr21:44318373:44333972"
[1] "Hit: chr21:46560625:46602991"
[1] "Hit: chr21:46636799:46654120"
[1] "Starting Chromosome: 22"
[1] "Hit: chr22:16783315:16808181"
[1] "Hit: chr22:20061433:20087419"
[1] "Hit: chr22:22339476:22588786"
[1] "Hit: chr22:22427443:22896209"
[1] "Hit: chr22:23149966:23159351"
[1] "Hit: chr22:28772577:28786891"
[1] "Hit: chr22:37734302:37741130"
[1] "Hit: chr22:40819098:40909333"
[1] "Hit: chr22:41673836:41694397"
[1] "Hit: chr22:41693366:41718372"
[1] "Hit: chr22:41976713:41987857"
[1] "Hit: chr22:43886206:43889636"
[1] "Hit: chr22:49773186:49777911"
[1] "Hit: chr22:49902840:49908042"

Time difference of 56.13 secs

In [65]:
head(total_results)

  change                   zeros ones zero_ids  one_ids
1 chr1:103525603:103552876 0     0           NA        NA
2 chr1:109235113:109238280 0     0           NA        NA
3 chr1:109279459:109281327 0     1           NA AU4991301
4 chr1:11029562:11045765   1     0    AU4963301        NA
5 chr1:11037596:11045765   0     1           NA AU4891301
6 chr1:12755603:12776216   0     0           NA        NA

In [69]:
10926251>=109238280

[1] FALSE

In [66]:
dim(total_results)

[1] 412   5

In [39]:
table(total_results$ones)

  0   1   2   3   4   5   6
262 119  52   6  20   5   6

In [40]:
filtered <- total_results[total_results$zeros > 0 | total_results$ones > 0,]

In [41]:
dim(filtered)

[1] 236   5

In [43]:
total_results$EUR <- total_results$zero_ids

In [44]:
total_results$AFR <- total_results$one_ids

In [46]:
total_results$n_EUR <- total_results$zeros

In [47]:
total_results$n_AFR <- total_results$ones

In [48]:
head(var_indv)

  change                    sampleIDs            chr start     end
1 chr10:113583119:113731005 AU4935301            10  113583119 113731005
2 chr10:122488805:122566094 DG1015-302           10  122488805 122566094
3 chr10:122585174:122590792 AU1324303            10  122585174 122590792
4 chr10:122585174:122598110 DG1076-301           10  122585174 122598110
5 chr10:122597877:122600191 AU4946302, AU4784303 10  122597877 122600191
6 chr10:122832061:122850648 DG1069-301           10  122832061 122850648

In [50]:
total_results <- left_join(total_results, var_indv[,c("change", "chr", "start", "end")])

Joining with `by = join_by(change)`

In [51]:
head(total_results)

  change                   zeros ones zero_ids  one_ids   EUR       AFR
1 chr1:103525603:103552876 0     0    NA        NA        NA        NA
2 chr1:109235113:109238280 0     0    NA        NA        NA        NA
3 chr1:109279459:109281327 0     1    NA        AU4991301 NA        AU4991301
4 chr1:11029562:11045765   1     0    AU4963301 NA        AU4963301 NA
5 chr1:11037596:11045765   0     1    NA        AU4891301 NA        AU4891301
6 chr1:12755603:12776216   0     0    NA        NA        NA        NA
  n_EUR n_AFR chr start     end
1 0     0     1   103525603 103552876
2 0     0     1   109235113 109238280
3 0     1     1   109279459 109281327
4 1     0     1    11029562  11045765
5 0     1     1    11037596  11045765
6 0     0     1    12755603  12776216

In [53]:
final_df <- total_results[,c("change", "chr", "start", "end", "n_EUR", "n_AFR", "EUR", "AFR")]

In [52]:
write_csv(total_results, "ad3_window.csv")

In [54]:
head(final_df)

  change                   chr start     end       n_EUR n_AFR EUR
1 chr1:103525603:103552876 1   103525603 103552876 0     0     NA
2 chr1:109235113:109238280 1   109235113 109238280 0     0     NA
3 chr1:109279459:109281327 1   109279459 109281327 0     1     NA
4 chr1:11029562:11045765   1    11029562  11045765 1     0     AU4963301
5 chr1:11037596:11045765   1    11037596  11045765 0     1     NA
6 chr1:12755603:12776216   1    12755603  12776216 0     0     NA
  AFR
1 NA
2 NA
3 AU4991301
4 NA
5 AU4891301
6 NA

In [56]:
write_csv(final_df, "ad3_info.csv")

In [57]:
sum(final_df$n_EUR)

[1] 38

In [58]:
sum(final_df$n_AFR)

[1] 382

In [25]:
var_2 <- var_indv[var_indv$chr == 2,]

In [26]:
head(var_2)

  change                   sampleIDs  chr start     end
1 chr2:10052130:10211823   AU4591301  2   10052130  10211823
2 chr2:110115591:110212973 DG1246-301 2   110115591 110212973
3 chr2:111940205:112029659 AU4734301  2   111940205 112029659
4 chr2:120127591:120294808 DG1158-301 2   120127591 120294808
5 chr2:127279076:127324339 AU3128302  2   127279076 127324339
6 chr2:130313837:130375503 DG1040-302 2   130313837 130375503

In [30]:
find_regions(var_2, test_msp)

[1] "Overlapping variant window: chr2:110115591:110212973"
[1] "Overlapping variant window: chr2:111940205:112029659"
[1] "Overlapping variant window: chr2:120127591:120294808"
[1] "Overlapping variant window: chr2:127279076:127324339"
[1] "Overlapping variant window: chr2:130313837:130375503"
[1] "Overlapping variant window: chr2:130330045:130375503"
[1] "Overlapping variant window: chr2:130728973:131147440"
[1] "Overlapping variant window: chr2:130837358:131147440"
[1] "Overlapping variant window: chr2:147917186:147948322"
[1] "Overlapping variant window: chr2:147972642:147976073"
[1] "Overlapping variant window: chr2:189441349:189488090"
[1] "Overlapping variant window: chr2:189741245:189755658"
[1] "Overlapping variant window: chr2:199935834:199940231"
[1] "Overlapping variant window: chr2:206745525:206749281"
[1] "Overlapping variant window: chr2:208170848:208187159"
[1] "Overlapping variant window: chr2:217803770:217831645"
[1] "Overlapping variant window: chr2:227080346:227147682"
[1] "Overlapping variant window: chr2:227472035:227525013"
[1] "Overlapping variant window: chr2:23958204:24000544"
[1] "Overlapping variant window: chr2:240716497:240769804"
[1] "Overlapping variant window: chr2:241735020:241744975"
[1] "Overlapping variant window: chr2:26516321:26562784"
[1] "Overlapping variant window: chr2:27439669:27455521"
[1] "Overlapping variant window: chr2:28495963:28529877"
[1] "Overlapping variant window: chr2:28495963:28532292"
[1] "Overlapping variant window: chr2:32406402:32949043"
[1] "Overlapping variant window: chr2:32406402:33021304"
[1] "Overlapping variant window: chr2:32493443:32949043"
[1] "Overlapping variant window: chr2:33549507:33563739"
[1] "Overlapping variant window: chr2:36551959:36560963"
[1] "Overlapping variant window: chr2:36551959:36583567"
[1] "Overlapping variant window: chr2:36551959:36598289"
[1] "Overlapping variant window: chr2:38295714:38319117"
[1] "Overlapping variant window: chr2:44299874:44315341"
[1] "Overlapping variant window: chr2:44319328:44323509"
[1] "Overlapping variant window: chr2:47369275:47380067"
[1] "Overlapping variant window: chr2:50829345:51028347"
[1] "Overlapping variant window: chr2:55683688:55687803"
[1] "Overlapping variant window: chr2:65253631:65265273"
[1] "Overlapping variant window: chr2:75646686:75666151"
[1] "Overlapping variant window: chr2:79120265:79159851"
[1] "Overlapping variant window: chr2:85389451:85402256"
[1] "Overlapping variant window: chr2:97348802:97659989"

   variant                  zeros ones
1  chr2:10052130:10211823   0     0
2  chr2:110115591:110212973 0     0
3  chr2:111940205:112029659 0     3
4  chr2:120127591:120294808 0     0
5  chr2:127279076:127324339 0     3
6  chr2:130313837:130375503 0     0
7  chr2:130330045:130375503 0     0
8  chr2:130728973:131147440 0     0
9  chr2:130837358:131147440 0     2
10 chr2:1422948:1517080     0     0
11 chr2:1433341:1517080     0     0
12 chr2:147917186:147948322 0     1
13 chr2:147972642:147976073 0     2
14 chr2:15275387:15561432   1     0
15 chr2:189441349:189488090 0     0
16 chr2:189741245:189755658 0     0
17 chr2:199935834:199940231 0     1
18 chr2:206745525:206749281 0     2
19 chr2:208170848:208187159 0     0
20 chr2:217803770:217831645 0     0
21 chr2:218124:243660       0     0
22 chr2:227080346:227147682 0     2
23 chr2:227472035:227525013 1     1
24 chr2:23958204:24000544   0     3
25 chr2:240716497:240769804 0     0
26 chr2:241735020:241744975 1     0
27 chr2:26516321:26562784   0     0
28 chr2:27439669:27455521   0     0
29 chr2:28495963:28529877   0     2
30 chr2:28495963:28532292   0     1
31 chr2:32406402:32949043   0     2
32 chr2:32406402:33021304   0     2
33 chr2:32493443:32949043   0     0
34 chr2:33549507:33563739   0     0
35 chr2:36551959:36560963   0     0
36 chr2:36551959:36583567   1     4
37 chr2:36551959:36598289   0     3
38 chr2:38295714:38319117   0     0
39 chr2:44299874:44315341   0     0
40 chr2:44319328:44323509   1     1
41 chr2:47369275:47380067   0     2
42 chr2:50829345:51028347   0     0
43 chr2:55683688:55687803   0     0
44 chr2:65253631:65265273   0     2
45 chr2:668850:677571       0     1
46 chr2:75646686:75666151   0     0
47 chr2:79120265:79159851   0     0
48 chr2:85389451:85402256   0     0
49 chr2:97348802:97659989   1     0