In [1]:
library(tidyverse)
library(data.table)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.6
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()


Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose

In [2]:
library(biomaRt)

In [3]:
eqtl <- fread("DER-08a_hg38_eQTL.significant.txt")

In [7]:
# http://resource.psychencode.org/
# total in hg 19
# how they filter in next set:
#     Set with FDR<0.05 and a filter requiring genes to have an expression > 0.1 FPKM in at least 10 samples
# filtered in hg 38

In [4]:
head(eqtl)

  gene_id           gene_chr gene_start gene_end strand number_of_SNPs_tested
1 ENSG00000215004.3 chr3     29087396   29087396 +      4558
2 ENSG00000215004.3 chr3     29087396   29087396 +      4558
3 ENSG00000215004.3 chr3     29087396   29087396 +      4558
4 ENSG00000215004.3 chr3     29087396   29087396 +      4558
5 ENSG00000215004.3 chr3     29087396   29087396 +      4558
6 ENSG00000215004.3 chr3     29087396   29087396 +      4558
  SNP_distance_to_TSS SNP_id     SNP_chr SNP_start SNP_end  nominal_pval
1 -365581             3:28721815 chr3    28721815  28721815 0.000270335
2 -364465             3:28722931 chr3    28722931  28722931 0.000344220
3 -364376             3:28723020 chr3    28723020  28723020 0.000523559
4 -357186             3:28730210 chr3    28730210  28730210 0.000606794
5  276595             3:29363991 chr3    29363991  29363991 0.000509309
6  753189             3:29840585 chr3    29840585  29840585 0.000525076
  regression_slope top_SNP FDR
1  0.0886898       1       0.01979050
2  0.0868007       0       0.02424459
3  0.0841030       0       0.03431670
4  0.0861309       0       0.03870841
5 -0.5076670       0       0.03355055
6  0.0807715       0       0.03439850

In [3]:
#colnames(eqtl) <- c("gene_id", "gene_chr", "gene_start", "gene_end", "strand", 
#                    "number_of_SNPs_tested", "SNP_distance_to_TSS", "SNP_id", "SNP_chr", "SNP_start", "SNP_end",
#                   "nomimal_pval", "regression_slope", "top_SNP")

In [5]:
table(table(eqtl$gene_id))

   1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16
4443 2773 2059 1504 1048  988  769  683  611  472  456  395  385  365  332  298
  17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32
 280  223  220  227  217  205  186  192  189  176  182  154  164  147  150  132
  33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48
 142  145  133  121  125  118  119  108  115  118  103   90  103   95   92   87
  49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64
  97   96   98   80   98   74   90   80   63   87  106   74   63   82   82   81
  65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80
  55   83   70   63   66   69   63   82   65   69   58   56   47   71   48   53
  81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96
  64   54   55   40   50   74   50   61   52   47   49   63   50   63   40   62
  97   98   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  62   46   51   44   51   58   41   51   53   46   54   50   32   41   45   31
 113  114  115  116  117  118  119  120  121  122  123  124  125  126  127  128
  52   46   38   39   32   39   44   37   37   43   35   37   45   39   47   35
 129  130  131  132  133  134  135  136  137  138  139  140  141  142  143  144
  46   34   44   29   36   33   31   32   34   30   37   32   26   40   27   30
 145  146  147  148  149  150  151  152  153  154  155  156  157  158  159  160
  46   38   31   27   33   39   21   38   40   27   29   27   29   26   26   28
 161  162  163  164  165  166  167  168  169  170  171  172  173  174  175  176
  30   22   17   30   31   25   35   37   23   33   21   26   32   34   26   37
 177  178  179  180  181  182  183  184  185  186  187  188  189  190  191  192
  20   25   27   23   26   23   28   26   15   25   29   26   17   29   31   19
 193  194  195  196  197  198  199  200  201  202  203  204  205  206  207  208
  26   25   25   26   19   20   17   18   24   16   28   23   23   32   20   17
 209  210  211  212  213  214  215  216  217  218  219  220  221  222  223  224
  17   24   24   17   14   21   24   19   14   18   25   11   21   16   15   26
 225  226  227  228  229  230  231  232  233  234  235  236  237  238  239  240
  13   20    7   21   14   19   24   27   15   18   11   11   18   25   18   20
 241  242  243  244  245  246  247  248  249  250  251  252  253  254  255  256
  17   18   10   10   16   19   21   12   12   18   12   13   10   17   10   12
 257  258  259  260  261  262  263  264  265  266  267  268  269  270  271  272
  16   14   18   15   15   11   14   17   18   16   16   10   20   12   16    9
 273  274  275  276  277  278  279  280  281  282  283  284  285  286  287  288
  13    8   18   16   19    6   15   12    8   12   10   13   12   10   12   14
 289  290  291  292  293  294  295  296  297  298  299  300  301  302  303  304
   9    5   12    7   10   12   11   10    9   15   12    5   10    6    4   10
 305  306  307  308  309  310  311  312  313  314  315  316  317  318  319  320
  11    7    9   21   14   12   12   12   11    5    9    8    8    7   10    9
 321  322  323  324  325  326  327  328  329  330  331  332  333  334  335  336
  11    8   12    6   10    9    5   10    3   13   13   12   12    7    6    8
 337  338  339  340  341  342  343  344  345  346  347  348  349  350  351  352
  11   13   14   10    5   16   10    8   10    9    8   11   11    9    7    7
 353  354  355  356  357  358  359  360  361  362  363  364  365  366  367  368
   6    8   13   10    7    9    9    6    6    8    6    9    8   11    4   15
 369  370  371  372  373  374  375  376  377  378  379  380  381  382  383  384
   6   14    9    6    8    8    6    9    7    9    4    3    4    8   10    7
 385  386  387  388  389  390  391  392  393  394  395  396  397  398  399  400
   9    2   11   10    7    8    6    9    3    5    4    4    2    5    7    8
 401  402  403  404  405  406  407  408  409  410  411  412  413  414  415  416
   9    7    5    6    9    8    5    7   10    6    5    7   10    6    5    3
 417  418  419  420  421  422  423  424  425  426  427  428  429  430  431  432
   5    9    5    3    4    4    2    6    8    5    3    3    1    7    4    2
 433  434  435  436  437  438  439  440  441  442  443  444  445  446  447  448
   5    6    6    4    5    8    7    5    4    9    3    6    6    4    9    7
 449  450  451  452  454  455  456  457  458  459  460  461  462  463  464  465
   2    6    9    5    4    4    6    3    3   10    2    6    5    8    4    4
 466  467  468  469  470  471  472  473  474  475  476  477  478  479  480  481
   5    2    5    5    1    2    3    2    3    6    3    5    4    5    3    8
 482  483  484  485  486  487  488  489  490  491  492  493  494  495  496  497
   6    5    2    4    8    4    2    5    5    5    6    5    3    3    4    6
 498  499  501  502  503  504  505  506  507  508  509  510  511  512  513  514
   8    2    3    4    5    4    4    2    1    2    3    5    7    1    2    4
 515  516  517  518  519  520  521  522  523  524  525  526  527  528  529  530
   4    2    5    4    1    4    3    4    4    5    4    2    3    1    4    2
 531  532  533  534  535  536  537  538  539  540  541  542  543  544  545  546
   2    3    5    7    2    3    4    1    5    3   10    1    2    3    3    2
 547  548  549  550  551  552  553  554  555  556  557  558  559  561  562  563
   3    2    1    2    2    2    3    2    5    2    3    3    5    4    3    5
 564  565  566  567  568  569  570  571  572  573  574  575  576  578  579  580
   6    2    2    3    6    1    4    1    2    3    2    2    3    1    1    2
 582  583  584  585  586  587  588  589  590  591  592  593  594  595  596  597
   4    4    1    1    3    2    1    1    2    3    1    3    4    2    2    4
 598  599  600  601  602  604  605  606  607  608  609  610  611  612  613  614
   4    1    2    3    2    5    1    1    1    2    2    5    1    3    3    4
 615  616  617  618  619  620  621  622  623  624  625  626  627  629  630  632
   3    1    1    3    3    5    3    3    3    2    4    2    2    3    3    3
 633  634  635  636  637  638  639  640  641  642  643  644  645  646  647  648
   1    1    2    1    1    1    1    2    3    5    3    3    1    2    7    3
 649  650  651  652  654  655  657  658  659  660  661  662  663  665  666  667
   1    1    4    1    3    3    2    2    3    1    1    3    2    1    5    1
 668  669  670  671  672  673  674  675  676  677  678  680  681  682  683  684
   4    1    1    2    3    2    2    2    2    2    2    2    1    2    4    3
 685  686  687  688  689  690  691  693  694  696  698  699  700  702  703  704
   1    3    2    1    1    2    1    1    1    3    1    3    1    1    1    1
 705  708  709  710  711  712  713  714  715  716  717  719  720  722  723  724
   3    2    2    1    2    1    2    3    1    1    1    2    2    1    1    1
 725  726  727  728  730  731  733  737  738  739  741  742  744  745  746  747
   2    2    1    1    1    5    4    1    2    4    1    6    3    1    2    4
 750  751  752  754  756  758  759  760  762  768  769  773  774  775  776  777
   2    3    1    2    4    1    1    1    1    1    3    1    2    2    1    2
 778  779  780  784  785  786  787  788  791  792  795  796  797  799  800  801
   1    2    1    1    3    3    2    1    1    3    1    1    1    2    1    2
 802  804  805  808  810  811  812  814  815  817  818  821  822  823  824  825
   1    1    2    1    2    1    1    1    2    1    1    2    1    2    1    1
 826  830  833  834  835  836  837  838  839  840  843  844  846  848  849  850
   1    2    1    5    1    1    1    1    2    1    2    1    1    1    1    2
 851  853  854  855  856  858  859  861  864  865  872  877  879  881  882  883
   1    2    1    1    1    1    2    1    1    1    3    1    3    1    1    2
 884  885  888  890  891  893  895  896  897  900  902  903  908  909  910  913
   2    2    1    1    1    1    1    1    1    3    1    1    2    2    1    1
 915  916  920  922  925  927  944  951  952  954  956  958  961  966  967  968
   1    1    2    2    1    1    1    2    2    1    1    1    3    1    2    1
 969  970  971  973  974  976  979  980  983  984  986  988  991  992  996  998
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    2    2
1000 1002 1007 1014 1021 1026 1030 1031 1032 1038 1042 1052 1055 1061 1066 1067
   1    1    1    1    3    1    1    2    2    2    1    1    1    1    1    2
1075 1076 1088 1096 1106 1110 1111 1113 1117 1123 1125 1127 1130 1131 1132 1133
   1    1    1    1    1    2    1    1    1    1    1    1    1    1    2    1
1136 1140 1143 1145 1149 1154 1158 1161 1163 1166 1181 1188 1198 1207 1217 1224
   1    1    1    1    1    1    1    1    1    1    1    2    1    1    1    1
1228 1242 1244 1251 1255 1261 1272 1292 1300 1301 1303 1304 1305 1329 1331 1335
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    2
1338 1340 1341 1344 1349 1352 1357 1360 1373 1378 1379 1382 1383 1405 1410 1412
   1    1    1    1    1    1    1    2    1    1    1    1    1    1    1    1
1422 1425 1429 1445 1452 1455 1456 1465 1468 1473 1474 1482 1498 1501 1507 1530
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1
1537 1544 1547 1550 1567 1569 1586 1612 1618 1639 1746 1787 1897 1899 1939 1941
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1
1953 1986 1994 1995 2035 2040 2126 2128 2130 2271 2497 3173 3346 3773 3792 3819
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1
3988
   1

In [4]:
head(eqtl)

  gene_id           gene_chr gene_start gene_end strand number_of_SNPs_tested
1 ENSG00000215004.3 chr3     29128887   29128887 +      4558
2 ENSG00000215004.3 chr3     29128887   29128887 +      4558
3 ENSG00000215004.3 chr3     29128887   29128887 +      4558
4 ENSG00000215004.3 chr3     29128887   29128887 +      4558
5 ENSG00000215004.3 chr3     29128887   29128887 +      4558
6 ENSG00000215004.3 chr3     29128887   29128887 +      4558
  SNP_distance_to_TSS SNP_id     SNP_chr SNP_start SNP_end  nomimal_pval
1 -998415             3:28130472 chr3    28130472  28130472 0.935933
2 -998201             3:28130686 chr3    28130686  28130686 0.934622
3 -996771             3:28132116 chr3    28132116  28132116 0.445269
4 -996343             3:28132544 chr3    28132544  28132544 0.351889
5 -996026             3:28132861 chr3    28132861  28132861 0.116941
6 -995791             3:28133096 chr3    28133096  28133096 0.582236
  regression_slope top_SNP
1  0.00173423      0
2  0.00183973      0
3  0.01641450      0
4 -0.05048720      0
5  0.06831040      0
6  0.01208210      0

In [11]:
range(eqtl$nomimal_pval)

[1] 2.22507e-308  1.00000e+00

In [5]:
dim(eqtl)

[1] 152573869        14

In [10]:
length(unique(eqtl$gene_id))

[1] 32939

In [7]:

# Split the column into two based on the "." delimiter
split_df <- do.call(rbind, strsplit(as.character(eqtl$gene_id), "\\."))

# Combine the split columns back into the data frame
eqtl$ensgid <- split_df[, 1]
eqtl$ensgid_v <- split_df[, 2]

In [8]:
head(eqtl)

  gene_id           gene_chr gene_start gene_end strand number_of_SNPs_tested
1 ENSG00000215004.3 chr3     29087396   29087396 +      4558
2 ENSG00000215004.3 chr3     29087396   29087396 +      4558
3 ENSG00000215004.3 chr3     29087396   29087396 +      4558
4 ENSG00000215004.3 chr3     29087396   29087396 +      4558
5 ENSG00000215004.3 chr3     29087396   29087396 +      4558
6 ENSG00000215004.3 chr3     29087396   29087396 +      4558
  SNP_distance_to_TSS SNP_id     SNP_chr SNP_start SNP_end  nominal_pval
1 -365581             3:28721815 chr3    28721815  28721815 0.000270335
2 -364465             3:28722931 chr3    28722931  28722931 0.000344220
3 -364376             3:28723020 chr3    28723020  28723020 0.000523559
4 -357186             3:28730210 chr3    28730210  28730210 0.000606794
5  276595             3:29363991 chr3    29363991  29363991 0.000509309
6  753189             3:29840585 chr3    29840585  29840585 0.000525076
  regression_slope top_SNP FDR        ensgid          ensgid_v
1  0.0886898       1       0.01979050 ENSG00000215004 3
2  0.0868007       0       0.02424459 ENSG00000215004 3
3  0.0841030       0       0.03431670 ENSG00000215004 3
4  0.0861309       0       0.03870841 ENSG00000215004 3
5 -0.5076670       0       0.03355055 ENSG00000215004 3
6  0.0807715       0       0.03439850 ENSG00000215004 3

In [9]:
# Connect to Ensembl
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# The gene ID (strip version if necessary)
ensembl_ids <- unique(eqtl$ensgid)
# Get HGNC gene symbols
gene_ids <- getBM(attributes = c('ensembl_gene_id', 'hgnc_symbol'),
                filters = 'ensembl_gene_id',
                values = ensembl_ids,
                mart = ensembl)

In [10]:
head(gene_ids)

  ensembl_gene_id hgnc_symbol
1 ENSG00000000419 DPM1
2 ENSG00000000457 SCYL3
3 ENSG00000000460 FIRRM
4 ENSG00000001167 NFYA
5 ENSG00000002549 LAP3
6 ENSG00000002587 HS3ST1

In [11]:
dim(gene_ids)

[1] 30729     2

In [12]:
colnames(gene_ids) <- c("ensgid", "hgnc_symbol")

In [13]:
write.csv(gene_ids, "eqtl_gene_names.csv")

In [20]:
typeof(table(gene_ids$ensgid))

[1] "integer"

In [18]:
table(table(eqtl$ensgid))

   1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16
4443 2773 2059 1503 1048  988  769  684  611  472  456  395  385  365  332  298
  17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32
 280  223  220  227  217  205  186  192  189  176  182  154  164  147  150  132
  33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48
 142  145  133  121  125  118  119  108  115  118  103   90  103   95   92   87
  49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64
  97   96   98   80   98   74   90   80   63   87  106   74   63   82   82   81
  65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80
  55   83   70   63   66   69   63   82   65   69   58   56   47   71   48   53
  81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96
  64   54   55   40   50   74   50   61   52   47   49   63   50   63   40   62
  97   98   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  62   46   51   44   51   58   41   51   53   46   54   50   32   41   45   31
 113  114  115  116  117  118  119  120  121  122  123  124  125  126  127  128
  52   46   38   39   32   39   44   37   37   43   35   37   45   39   47   35
 129  130  131  132  133  134  135  136  137  138  139  140  141  142  143  144
  46   34   44   29   36   33   31   32   34   30   37   32   26   40   27   30
 145  146  147  148  149  150  151  152  153  154  155  156  157  158  159  160
  46   38   31   27   33   39   21   38   40   27   29   27   29   26   26   28
 161  162  163  164  165  166  167  168  169  170  171  172  173  174  175  176
  30   22   17   30   31   25   35   37   23   33   21   26   32   34   26   37
 177  178  179  180  181  182  183  184  185  186  187  188  189  190  191  192
  20   25   27   23   26   23   28   26   15   25   29   26   17   29   31   19
 193  194  195  196  197  198  199  200  201  202  203  204  205  206  207  208
  26   25   25   26   19   20   17   18   24   16   28   23   23   32   20   17
 209  210  211  212  213  214  215  216  217  218  219  220  221  222  223  224
  17   24   24   17   14   21   24   19   14   18   25   11   21   16   15   26
 225  226  227  228  229  230  231  232  233  234  235  236  237  238  239  240
  13   20    7   21   14   19   24   27   15   18   11   11   18   25   18   20
 241  242  243  244  245  246  247  248  249  250  251  252  253  254  255  256
  17   18   10   10   16   19   21   12   12   18   12   13   10   17   10   12
 257  258  259  260  261  262  263  264  265  266  267  268  269  270  271  272
  16   14   18   15   15   11   14   17   18   16   16   10   20   12   16    9
 273  274  275  276  277  278  279  280  281  282  283  284  285  286  287  288
  13    8   18   16   19    6   15   12    8   12   10   13   12   10   12   14
 289  290  291  292  293  294  295  296  297  298  299  300  301  302  303  304
   9    5   12    7   10   12   11   10    9   15   12    5   10    6    4   10
 305  306  307  308  309  310  311  312  313  314  315  316  317  318  319  320
  11    7    9   21   14   12   12   12   11    5    9    8    8    7   10    9
 321  322  323  324  325  326  327  328  329  330  331  332  333  334  335  336
  11    8   12    6   10    9    5   10    3   13   13   12   12    7    6    8
 337  338  339  340  341  342  343  344  345  346  347  348  349  350  351  352
  11   13   14   10    5   16   10    8   10    9    8   11   11    9    7    7
 353  354  355  356  357  358  359  360  361  362  363  364  365  366  367  368
   6    8   13   10    7    9    9    6    6    8    6    9    8   11    4   15
 369  370  371  372  373  374  375  376  377  378  379  380  381  382  383  384
   6   14    9    6    8    8    6    9    7    9    4    3    4    8   10    7
 385  386  387  388  389  390  391  392  393  394  395  396  397  398  399  400
   9    2   11   10    7    8    6    9    3    5    4    4    2    5    7    8
 401  402  403  404  405  406  407  408  409  410  411  412  413  414  415  416
   9    7    5    6    9    8    5    7   10    6    5    7   10    6    5    3
 417  418  419  420  421  422  423  424  425  426  427  428  429  430  431  432
   5    9    5    3    4    4    2    6    8    5    3    3    1    7    4    2
 433  434  435  436  437  438  439  440  441  442  443  444  445  446  447  448
   5    6    6    4    5    8    7    5    4    9    3    6    6    4    9    7
 449  450  451  452  454  455  456  457  458  459  460  461  462  463  464  465
   2    6    9    5    4    4    6    3    3   10    2    6    5    8    4    4
 466  467  468  469  470  471  472  473  474  475  476  477  478  479  480  481
   5    2    5    5    1    2    3    2    3    6    3    5    4    5    3    8
 482  483  484  485  486  487  488  489  490  491  492  493  494  495  496  497
   6    5    2    4    8    4    2    5    5    5    6    5    3    3    4    6
 498  499  501  502  503  504  505  506  507  508  509  510  511  512  513  514
   8    2    3    4    5    4    4    2    1    2    3    5    7    1    2    4
 515  516  517  518  519  520  521  522  523  524  525  526  527  528  529  530
   4    2    5    4    1    4    3    4    4    5    4    2    3    1    4    2
 531  532  533  534  535  536  537  538  539  540  541  542  543  544  545  546
   2    3    5    7    2    3    4    1    5    3   10    1    2    3    3    2
 547  548  549  550  551  552  553  554  555  556  557  558  559  561  562  563
   3    2    1    2    2    2    3    2    5    2    3    3    5    4    3    5
 564  565  566  567  568  569  570  571  572  573  574  575  576  578  579  580
   6    2    2    3    6    1    4    1    2    3    2    2    3    1    1    2
 582  583  584  585  586  587  588  589  590  591  592  593  594  595  596  597
   4    4    1    1    3    2    1    1    2    3    1    3    4    2    2    4
 598  599  600  601  602  604  605  606  607  608  609  610  611  612  613  614
   4    1    2    3    2    5    1    1    1    2    2    5    1    3    3    4
 615  616  617  618  619  620  621  622  623  624  625  626  627  629  630  632
   3    1    1    3    3    5    3    3    3    2    4    2    2    3    3    3
 633  634  635  636  637  638  639  640  641  642  643  644  645  646  647  648
   1    1    2    1    1    1    1    2    3    5    3    3    1    2    7    3
 649  650  651  652  654  655  657  658  659  660  661  662  663  665  666  667
   1    1    4    1    3    3    2    2    3    1    1    3    2    1    5    1
 668  669  670  671  672  673  674  675  676  677  678  680  681  682  683  684
   4    1    1    2    3    2    2    2    2    2    2    2    1    2    4    3
 685  686  687  688  689  690  691  693  694  696  698  699  700  702  703  704
   1    3    2    1    1    2    1    1    1    3    1    3    1    1    1    1
 705  708  709  710  711  712  713  714  715  716  717  719  720  722  723  724
   3    2    2    1    2    1    2    3    1    1    1    2    2    1    1    1
 725  726  727  728  730  731  733  737  738  739  741  742  744  745  746  747
   2    2    1    1    1    5    4    1    2    4    1    6    3    1    2    4
 750  751  752  754  756  758  759  760  762  768  769  773  774  775  776  777
   2    3    1    2    4    1    1    1    1    1    3    1    2    2    1    2
 778  779  780  784  785  786  787  788  791  792  795  796  797  799  800  801
   1    2    1    1    3    3    2    1    1    3    1    1    1    2    1    2
 802  804  805  808  810  811  812  814  815  817  818  821  822  823  824  825
   1    1    2    1    2    1    1    1    2    1    1    2    1    2    1    1
 826  830  833  834  835  836  837  838  839  840  843  844  846  848  849  850
   1    2    1    5    1    1    1    1    2    1    2    1    1    1    1    2
 851  853  854  855  856  858  859  861  864  865  872  877  879  881  882  883
   1    2    1    1    1    1    2    1    1    1    3    1    3    1    1    2
 884  885  888  890  891  893  895  896  897  900  902  903  908  909  910  913
   2    2    1    1    1    1    1    1    1    3    1    1    2    2    1    1
 915  916  920  922  925  927  944  951  952  954  956  958  961  966  967  968
   1    1    2    2    1    1    1    2    2    1    1    1    3    1    2    1
 969  970  971  973  974  976  979  980  983  984  986  988  991  992  996  998
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    2    2
1000 1002 1007 1014 1021 1026 1030 1031 1032 1038 1042 1052 1055 1061 1066 1067
   1    1    1    1    3    1    1    2    2    2    1    1    1    1    1    2
1075 1076 1088 1096 1106 1110 1111 1113 1117 1123 1125 1127 1130 1131 1132 1133
   1    1    1    1    1    2    1    1    1    1    1    1    1    1    2    1
1136 1140 1143 1145 1149 1154 1158 1161 1163 1166 1181 1188 1198 1207 1217 1224
   1    1    1    1    1    1    1    1    1    1    1    2    1    1    1    1
1228 1242 1244 1251 1255 1261 1272 1292 1300 1301 1303 1304 1305 1329 1331 1335
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    2
1338 1340 1341 1344 1349 1352 1357 1360 1373 1378 1379 1382 1383 1405 1410 1412
   1    1    1    1    1    1    1    2    1    1    1    1    1    1    1    1
1422 1425 1429 1445 1452 1455 1456 1465 1468 1473 1474 1482 1498 1501 1507 1530
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1
1537 1544 1547 1550 1567 1569 1586 1612 1618 1639 1746 1787 1897 1899 1939 1941
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1
1953 1986 1994 1995 2035 2040 2126 2128 2130 2271 2497 3173 3346 3773 3792 3819
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1
3988
   1

In [14]:
dim(eqtl)

[1] 2542119      17

In [15]:
eqtl <- left_join(eqtl, gene_ids, by = "ensgid")

In [16]:
dim(eqtl)

[1] 2542123      18

In [ ]:
# FDR

In [17]:
head(eqtl)

  gene_id           gene_chr gene_start gene_end strand number_of_SNPs_tested
1 ENSG00000215004.3 chr3     29087396   29087396 +      4558
2 ENSG00000215004.3 chr3     29087396   29087396 +      4558
3 ENSG00000215004.3 chr3     29087396   29087396 +      4558
4 ENSG00000215004.3 chr3     29087396   29087396 +      4558
5 ENSG00000215004.3 chr3     29087396   29087396 +      4558
6 ENSG00000215004.3 chr3     29087396   29087396 +      4558
  SNP_distance_to_TSS SNP_id     SNP_chr SNP_start SNP_end  nominal_pval
1 -365581             3:28721815 chr3    28721815  28721815 0.000270335
2 -364465             3:28722931 chr3    28722931  28722931 0.000344220
3 -364376             3:28723020 chr3    28723020  28723020 0.000523559
4 -357186             3:28730210 chr3    28730210  28730210 0.000606794
5  276595             3:29363991 chr3    29363991  29363991 0.000509309
6  753189             3:29840585 chr3    29840585  29840585 0.000525076
  regression_slope top_SNP FDR        ensgid          ensgid_v hgnc_symbol
1  0.0886898       1       0.01979050 ENSG00000215004 3        MESTP4
2  0.0868007       0       0.02424459 ENSG00000215004 3        MESTP4
3  0.0841030       0       0.03431670 ENSG00000215004 3        MESTP4
4  0.0861309       0       0.03870841 ENSG00000215004 3        MESTP4
5 -0.5076670       0       0.03355055 ENSG00000215004 3        MESTP4
6  0.0807715       0       0.03439850 ENSG00000215004 3        MESTP4

In [19]:
write.csv(eqtl,"eqtl_data.csv")