In [2]:
map1 = read.delim("1k_ref_bed/all_chr.bim", header=F, quote="")

In [3]:
dim(map1)

[1] 30723119        6

In [4]:
head(map1)

  V1 V2          V3 V4    V5 V6
1 1  1:10397:C:A 0  10397 A  C
2 1  1:10437:T:C 0  10437 C  T
3 1  1:10440:C:A 0  10440 A  C
4 1  1:10443:C:T 0  10443 T  C
5 1  1:10444:T:A 0  10444 A  T
6 1  1:10450:T:G 0  10450 G  T

In [5]:
map1["V4" == 858952,]

     V1 V2 V3 V4 V5 V6

In [9]:
map2 = read.delim("SPARK_20210118/old_bim/SPARKiwes_TopMed_chr1.22_rsID.MikeDB_SPARKdb155_rm.sexmismatch.49.maf0.01.geno0.05.hwe1e6.bim", header=F, quote="")

In [10]:
head(map2)

  V1 V2          V3 V4     V5 V6
1 1  rs138388092 0  802843 C  T
2 1  rs12127425  0  858952 A  G
3 1  rs12131377  0  859842 G  C
4 1  rs12132517  0  863421 A  G
5 1  rs147634896 0  864119 C  T
6 1  rs79373928  0  866156 G  T

In [8]:
paste(map2$V1[1], map2$V4[1], map2$V5[1], map2$V6[1], sep= ":")

[1] "1:802843:C:T"

In [12]:
#map2$id <- paste(map2$V1, map2$V4, map2$V5, map2$V6, sep= ":")
map2$V2 <- paste(map2$V1, map2$V4, map2$V6, map2$V5, sep= ":")

In [23]:
head(map2)

  V1 V2           V3 V4     V5 V6
1 1  1:802843:T:C 0  802843 C  T
2 1  1:858952:G:A 0  858952 A  G
3 1  1:859842:C:G 0  859842 G  C
4 1  1:863421:G:A 0  863421 A  G
5 1  1:864119:T:C 0  864119 C  T
6 1  1:866156:T:G 0  866156 G  T

In [8]:
table(map2$V3)

      0
5678744

In [4]:
dim(map2)

[1] 5678744       6

In [25]:
write.table(map2, file="SPARK_20210118/SPARKiwes_TopMed_chr1.22_rsID.MikeDB_SPARKdb155_rm.sexmismatch.49.maf0.01.geno0.05.hwe1e6.bim", sep="\t", col.names=F, row.names=F, quote=F )

In [13]:
length(which(map2$V2 %in% map1$V2))

[1] 5364635

In [20]:
common.snps = which(map2$V2 %in% map1$V2)

In [15]:
length(common.snps)

[1] 5364635

In [21]:
head(map2$V2[common.snps])

[1] "1:802843:T:C" "1:858952:G:A" "1:859842:C:G" "1:863421:G:A" "1:864119:T:C"
[6] "1:866156:T:G"

In [22]:
write.table(map2$V2[common.snps], file="list.snps", sep="\t", col.names=F, row.names=F, quote=F )