In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
king_ace <- read.table("/u/project/pasaniuc/afcarrol/Projects/20240521_ace_ibd/king_ace_related.kin")

In [3]:
head(king_ace)

  V1  V2              V3              V4    V5    V6     V7     V8     V9
1 FID ID1             ID2             N_SNP Z0    Phi    HetHet IBS0   HetConc
2 0   AN00090_AN00090 AN00493_AN00493 46850 1.000 0.0000 0.2185 0.1065 0.3068
3 0   AN00090_AN00090 AN00544_AN00544 46803 1.000 0.0000 0.2199 0.1074 0.3080
4 0   AN00090_AN00090 AN00764_AN00764 46850 1.000 0.0000 0.2195 0.1098 0.3076
5 0   AN00090_AN00090 AN01125_AN01125 46803 1.000 0.0000 0.2166 0.1094 0.3034
6 0   AN00090_AN00090 AN01410_AN01410 46803 1.000 0.0000 0.2195 0.1125 0.3088
  V10     V11     V12     V13     V14     V15     V16
1 HomIBS0 Kinship IBD1Seg IBD2Seg PropIBD InfType Error
2 -0.9506 0.0059  0.0083  0.0000  0.0042  UN      0
3 -0.9541 0.0055  0.0038  0.0000  0.0019  UN      0
4 -0.9998 0.0000  0.0108  0.0000  0.0054  UN      0
5 -1.0201 -0.0023 0.0152  0.0000  0.0076  UN      0
6 -1.0505 -0.0058 0.0000  0.0000  0.0000  UN      0

In [4]:
colnames(king_ace) <- as.character(unlist(king_ace[1, ]))
king_ace <- king_ace[-1, ]

In [5]:
head(king_ace)

  FID ID1             ID2             N_SNP Z0    Phi    HetHet IBS0   HetConc
2 0   AN00090_AN00090 AN00493_AN00493 46850 1.000 0.0000 0.2185 0.1065 0.3068
3 0   AN00090_AN00090 AN00544_AN00544 46803 1.000 0.0000 0.2199 0.1074 0.3080
4 0   AN00090_AN00090 AN00764_AN00764 46850 1.000 0.0000 0.2195 0.1098 0.3076
5 0   AN00090_AN00090 AN01125_AN01125 46803 1.000 0.0000 0.2166 0.1094 0.3034
6 0   AN00090_AN00090 AN01410_AN01410 46803 1.000 0.0000 0.2195 0.1125 0.3088
7 0   AN00090_AN00090 AN01971_AN01971 46803 1.000 0.0000 0.2196 0.1080 0.3081
  HomIBS0 Kinship IBD1Seg IBD2Seg PropIBD InfType Error
2 -0.9506 0.0059  0.0083  0.0000  0.0042  UN      0
3 -0.9541 0.0055  0.0038  0.0000  0.0019  UN      0
4 -0.9998 0.0000  0.0108  0.0000  0.0054  UN      0
5 -1.0201 -0.0023 0.0152  0.0000  0.0076  UN      0
6 -1.0505 -0.0058 0.0000  0.0000  0.0000  UN      0
7 -0.9673 0.0039  0.0053  0.0000  0.0027  UN      0

In [7]:
king_ace$ID1 <- sub(".*_", "", king_ace$ID1)
king_ace$ID2 <- sub(".*_", "", king_ace$ID2)

In [8]:
head(king_ace)

  FID ID1     ID2     N_SNP Z0    Phi    HetHet IBS0   HetConc HomIBS0 Kinship
2 0   AN00090 AN00493 46850 1.000 0.0000 0.2185 0.1065 0.3068  -0.9506 0.0059
3 0   AN00090 AN00544 46803 1.000 0.0000 0.2199 0.1074 0.3080  -0.9541 0.0055
4 0   AN00090 AN00764 46850 1.000 0.0000 0.2195 0.1098 0.3076  -0.9998 0.0000
5 0   AN00090 AN01125 46803 1.000 0.0000 0.2166 0.1094 0.3034  -1.0201 -0.0023
6 0   AN00090 AN01410 46803 1.000 0.0000 0.2195 0.1125 0.3088  -1.0505 -0.0058
7 0   AN00090 AN01971 46803 1.000 0.0000 0.2196 0.1080 0.3081  -0.9673 0.0039
  IBD1Seg IBD2Seg PropIBD InfType Error
2 0.0083  0.0000  0.0042  UN      0
3 0.0038  0.0000  0.0019  UN      0
4 0.0108  0.0000  0.0054  UN      0
5 0.0152  0.0000  0.0076  UN      0
6 0.0000  0.0000  0.0000  UN      0
7 0.0053  0.0000  0.0027  UN      0

In [9]:
king_ace <- king_ace[,-1]

In [11]:
ace_2nd <- king_ace[king_ace$Kinship >= (1/8),]

In [12]:
head(ace_2nd)

       ID1      ID2      N_SNP Z0    Phi    HetHet IBS0   HetConc HomIBS0
248614 AU009501 AU009504 46850 1.000 0.0000 0.2235 0.0002 0.3209  -0.0008
251127 AU009502 AU009504 46850 1.000 0.0000 0.2400 0.0004 0.3446  -0.0019
256153 AU020301 AU020303 46850 1.000 0.0000 0.2029 0.0443 0.3110  -0.2792
258663 AU020302 AU020303 46850 1.000 0.0000 0.2143 0.0001 0.3342  -0.0007
258664 AU020302 AU020305 46850 1.000 0.0000 0.2097 0.0003 0.3270  -0.0012
258665 AU020302 AU020306 46847 1.000 0.0000 0.2133 0.0003 0.3334  -0.0014
       Kinship IBD1Seg IBD2Seg PropIBD InfType Error
248614 0.2426  0.9942  0.0000  0.4971  PO      1
251127 0.2553  0.9929  0.0000  0.4964  PO      1
256153 0.1337  0.5300  0.0000  0.2650  2nd     1
258663 0.2501  0.9999  0.0000  0.5000  PO      1
258664 0.2458  0.9960  0.0000  0.4980  PO      1
258665 0.2494  0.9986  0.0000  0.4993  PO      1

In [20]:
dim(ace_2nd)

[1] 2346   15

In [13]:
write_csv(ace_2nd, "ace_2nd_relations.csv")

In [23]:
ace_dup <- ace_2nd[ace_2nd$InfType == "Dup/MZ",]

In [24]:
dim(ace_dup)

[1] 23 15

In [25]:
ace_dup

        ID1            ID2            N_SNP Z0    Phi    HetHet IBS0   HetConc
278715  AU026704       AU026705       46847 1.000 0.0000 0.4610 0.0000 0.9977
306182  AU062402dup    AU062402       46850 1.000 0.0000 0.4872 0.0000 0.9996
719928  AU1458307      AU1458308      46847 1.000 0.0000 0.4495 0.0000 0.9982
756912  AU1505302      AU1505303      46847 1.000 0.0000 0.5079 0.0000 0.9964
2178303 AU2911308      AU2911309      46847 1.000 0.0000 0.5172 0.0000 0.9977
2267652 AU3064304      AU3064305      46847 1.000 0.0000 0.4400 0.0000 0.9979
2744687 AU4513303      AU4513304      46850 1.000 0.0000 0.4677 0.0000 0.9995
2791140 AU4547302      AU4547303      46850 1.000 0.0000 0.4672 0.0000 0.9998
2886192 AU4634301      AU4634302      46850 1.000 0.0000 0.4516 0.0000 0.9999
2963928 AU4721302      AU4721303      46850 1.000 0.0000 0.5267 0.0000 0.9995
3099838 AU4882302      702-B-80312.01 46847 1.000 0.0000 0.4898 0.0000 0.9974
3190377 AU4988301      MH0180111      46844 1.000 0.0000 0.4652 0.0000 0.9973
3216215 AU5015302      AU5015303      46845 1.000 0.0000 0.4473 0.0000 0.9995
3225440 AU5028301      AU5028302      46845 1.000 0.0000 0.4553 0.0000 0.9998
3356340 DNAID65        DNAID68        46799 1.000 0.0000 0.4635 0.0000 0.9997
3384096 KP.BOS.400.03  KP864003       46844 1.000 0.0000 0.4652 0.0000 0.9996
3384321 KP.SEA.809.04  KP789604       46844 1.000 0.0000 0.4109 0.0000 0.9991
3384545 KP.SEA.810.03  KP524803       46844 1.000 0.0000 0.4889 0.0000 0.9994
3384768 KP.SEA.816.03  KP180403       46844 1.000 0.0000 0.4694 0.0000 0.9998
3391440 LOR105-302dup  LOR105-302     46762 1.000 0.0000 0.4681 0.0000 0.9950
3398033 LOR199-301dup  LOR199-301     46762 1.000 0.0000 0.4625 0.0000 0.9999
3398793 LOR211-301dup  LOR211-301     46762 1.000 0.0000 0.4757 0.0000 0.9998
3407783 702-A-80359.04 702-B-80335.03 46841 1.000 0.0000 0.4681 0.0001 0.9974
        HomIBS0 Kinship IBD1Seg IBD2Seg PropIBD InfType Error
278715  -0.0000 0.4994  0.0000  0.9981  0.9981  Dup/MZ  1
306182  -0.0000 0.4999  0.0000  1.0000  1.0000  Dup/MZ  1
719928  -0.0000 0.4995  0.0000  0.9990  0.9990  Dup/MZ  1
756912  -0.0000 0.4991  0.0000  0.9984  0.9984  Dup/MZ  1
2178303 -0.0000 0.4994  0.0022  0.9959  0.9970  Dup/MZ  1
2267652 -0.0000 0.4995  0.0000  0.9968  0.9968  Dup/MZ  1
2744687 -0.0000 0.4999  0.0000  0.9997  0.9997  Dup/MZ  1
2791140 -0.0000 0.4999  0.0000  0.9993  0.9993  Dup/MZ  1
2886192 -0.0000 0.5000  0.0000  0.9997  0.9997  Dup/MZ  1
2963928 -0.0000 0.4999  0.0000  1.0000  1.0000  Dup/MZ  1
3099838 -0.0000 0.4993  0.0051  0.9938  0.9963  Dup/MZ  1
3190377 -0.0000 0.4993  0.0000  0.9973  0.9973  Dup/MZ  1
3216215 -0.0000 0.4999  0.0000  1.0000  1.0000  Dup/MZ  1
3225440 -0.0000 0.5000  0.0000  1.0000  1.0000  Dup/MZ  1
3356340 -0.0000 0.4999  0.0000  0.9997  0.9997  Dup/MZ  1
3384096 -0.0000 0.4999  0.0000  1.0000  1.0000  Dup/MZ  1
3384321 -0.0000 0.4998  0.0000  1.0000  1.0000  Dup/MZ  1
3384545 -0.0000 0.4998  0.0000  0.9991  0.9991  Dup/MZ  1
3384768 -0.0000 0.4999  0.0000  1.0000  1.0000  Dup/MZ  1
3391440 -0.0000 0.4987  0.0043  0.9924  0.9945  Dup/MZ  1
3398033 -0.0000 0.5000  0.0000  1.0000  1.0000  Dup/MZ  1
3398793 -0.0000 0.4999  0.0000  1.0000  1.0000  Dup/MZ  1
3407783 -0.0001 0.4992  0.0021  0.9954  0.9964  Dup/MZ  1

In [21]:
mat_df <- ace_2nd[ace_2nd$ID1 == "AU020301" | ace_2nd$ID1 == "AU020301",]

In [22]:
mat_df

       ID1      ID2      N_SNP Z0    Phi    HetHet IBS0   HetConc HomIBS0
256153 AU020301 AU020303 46850 1.000 0.0000 0.2029 0.0443 0.3110  -0.2792
       Kinship IBD1Seg IBD2Seg PropIBD InfType Error
256153 0.1337  0.5300  0.0000  0.2650  2nd     1

In [26]:
write.csv(ace_dup, "ace_duplicates.csv")