In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
# Set the directory path containing the files
directory_path <- "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/"
# Initialize an empty data frame to store the results
result <- data.frame()

In [3]:
chrom <- 22

test_path <- paste0(directory_path, "chr", chrom, ".rfmix.Q")
print(test_path)

[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr22.rfmix.Q"

In [8]:
test_data <- read.table(test_path, header = F, sep = "\t")

In [10]:
colnames(test_data) <- c("IID", "CEU", "YRI")

In [11]:
head(test_data)

  IID                 CEU     YRI
1 AU003305_AU003305   0.98939 0.01061
2 AU0226302_AU0226302 1.00000 0.00000
3 AU0226303_AU0226303 1.00000 0.00000
4 AU025304_AU025304   1.00000 0.00000
5 AU025804_AU025804   0.98762 0.01238
6 MN.308_MN.308       1.00000 0.00000

In [12]:
# Loop through files from ace_chr1 to ace_chr22
for (chr in 1:22) {
    

  # Construct the file path
  file_path <- paste0(directory_path, "chr", chr, ".rfmix.Q")
  print(file_path)
  # Read the data from the current file
  data <- read.table(file_path, header = F, sep = "\t")
  colnames(data) <- c("IID", "CEU", "YRI")
  # Combine the results for each ancestry (ANC1 and ANC2)
  result <- rbind(result, data)
}

[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr1.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr2.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr3.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr4.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr5.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr6.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr7.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr8.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr9.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr10.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr11.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr12.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr13.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr14.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr15.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr16.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr17.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr18.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr19.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr20.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr21.rfmix.Q"
[1] "/u/project/geschwind/shared/PRS/20240223_ACE_RFMix/chr22.rfmix.Q"

In [14]:
head(result)

  IID                 CEU     YRI
1 AU003305_AU003305   0.98371 0.01629
2 AU0226302_AU0226302 0.98833 0.01167
3 AU0226303_AU0226303 0.98849 0.01151
4 AU025304_AU025304   0.97875 0.02125
5 AU025804_AU025804   0.97531 0.02469
6 MN.308_MN.308       0.99790 0.00210

In [15]:
dim(result)

[1] 57464     3

In [18]:
sum(is.na(result$YRI))

[1] 0

In [19]:
range(result$YRI)

[1] 0 1

In [26]:
# Sum the scores across all chromosomes for each individual by ancestry
final_result <- result %>%
  group_by(IID) %>%
  summarize(
    CEU_avg = mean(CEU),
    YRI_avg = mean(YRI)
  )

In [33]:
head(final_result)

  IID                           CEU_avg   YRI_avg    sum
1 702-A-80310.01_702-A-80310.01 0.9034686 0.09653136 0
2 702-A-80310.02_702-A-80310.02 0.9716968 0.02830318 0
3 702-A-80310.03_702-A-80310.03 0.9375468 0.06245318 0
4 702-A-80310.04_702-A-80310.04 0.9448155 0.05518455 0
5 702-A-80310.05_702-A-80310.05 0.9306032 0.06939682 0
6 702-A-80330.01_702-A-80330.01 0.9116609 0.08833909 0

In [35]:
final_result$sum <- final_result$CEU_avg + final_result$YRI_avg

In [38]:
head(final_result)

  IID                           CEU_avg   YRI_avg    sum
1 702-A-80310.01_702-A-80310.01 0.9034686 0.09653136 1
2 702-A-80310.02_702-A-80310.02 0.9716968 0.02830318 1
3 702-A-80310.03_702-A-80310.03 0.9375468 0.06245318 1
4 702-A-80310.04_702-A-80310.04 0.9448155 0.05518455 1
5 702-A-80310.05_702-A-80310.05 0.9306032 0.06939682 1
6 702-A-80330.01_702-A-80330.01 0.9116609 0.08833909 1

In [36]:
range(final_result$sum)

[1] 1 1

In [39]:
write_csv(final_result[,c("IID", "CEU_avg", "YRI_avg")], "ace_anc_part_prop.csv")