In [2]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [ ]:
######### didnt use these in the end - used hm3 filtered

In [3]:
one_kg <- read.table('/u/project/pasaniuc/afcarrol/Projects/20230930_1kg_variants/1kg_var.snplist')

In [4]:
one_kg$id <- paste("chr", one_kg$V1, sep = "")

In [5]:
# Split the entries by colon and store the result in a new data frame
#one_kg <- as.data.frame(do.call(rbind, strsplit(one_kg$V1, ":")))

# Rename the columns
colnames(one_kg) <- c("chrom", "pos", "ref", "alt")

ERROR: Error in names(x) <- value: 'names' attribute [4] must be the same length as the vector [2]

In [6]:
dim(one_kg)

[1] 443129      2

In [7]:
head(one_kg)

  V1           id
1 1:58814:G:A  chr1:58814:G:A
2 1:792461:G:A chr1:792461:G:A
3 1:817341:A:G chr1:817341:A:G
4 1:823656:G:A chr1:823656:G:A
5 1:858952:G:A chr1:858952:G:A
6 1:894801:A:G chr1:894801:A:G

In [8]:
map2 = read.delim("/u/project/pasaniuc/afcarrol/Projects/20230117_spark_pca_update/SPARK_20210118/SPARKiwes_TopMed_chr1.22_rsID.MikeDB_SPARKdb155_rm.sexmismatch.49.maf0.01.geno0.05.hwe1e6.bim", header=F, quote="")

In [9]:
head(map2)

  V1 V2       V3 V4     V5 V6
1 1  1:802843 0  802843 C  T
2 1  1:858952 0  858952 A  G
3 1  1:859842 0  859842 G  C
4 1  1:863421 0  863421 A  G
5 1  1:864119 0  864119 C  T
6 1  1:866156 0  866156 G  T

In [17]:
table(table(map2$V2))

      1
5678744

In [10]:
map2$V2 <- paste(map2$V1, map2$V4, map2$V6, map2$V5, sep= ":")

In [11]:
head(map2)

  V1 V2           V3 V4     V5 V6
1 1  1:802843:T:C 0  802843 C  T
2 1  1:858952:G:A 0  858952 A  G
3 1  1:859842:C:G 0  859842 G  C
4 1  1:863421:G:A 0  863421 A  G
5 1  1:864119:T:C 0  864119 C  T
6 1  1:866156:T:G 0  866156 G  T

In [12]:
length(which(map2$V2 %in% one_kg$V1))

[1] 275499

In [13]:
final_snps <- map2[map2$V2 %in% one_kg$V1 ,]

In [14]:
dim(final_snps)

[1] 275499      6

In [19]:
head(final_snps)

   V1 V2           V3 V4     V5 V6 out
2  1  1:858952:G:A 0  858952 A  G  1:858952
16 1  1:903285:T:C 0  903285 C  T  1:903285
25 1  1:905373:T:C 0  905373 C  T  1:905373
30 1  1:911428:C:T 0  911428 T  C  1:911428
44 1  1:916010:G:T 0  916010 T  G  1:916010
48 1  1:918870:A:G 0  918870 G  A  1:918870

In [18]:
final_snps$out <- paste(final_snps$V1, final_snps$V4, sep = ":")

In [20]:
map1 = read.delim("/u/project/pasaniuc/afcarrol/Projects/20230117_spark_pca_update/1k_ref_bed/all_chr.bim", header=F, quote="")

In [22]:
dim(map1)

[1] 30723119        6

In [1]:
head(map1)

ERROR: Error in head(map1): object 'map1' not found

In [20]:
write.table(final_snps$out, file="list.snps", sep="\t", col.names=F, row.names=F, quote=F )

In [23]:
writeLines(as.character(final_snps$V2), con = "filtered_snps_1kg_spark.txt")