In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.6
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [8]:
system("ls /u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms", intern = TRUE)

 [1] "2010-002.clean101007"        "2011-158.clean230815"
 [3] "2013-111A.ATN.clean170906"   "2013-438.clean230817"
 [5] "2015-9017.clean170906"       "2016-9174-3_clean190123"
 [7] "2016-9174_clean190123"       "2017-9154-merge_clean181212"
 [9] "2017-9154_merge_clean190118" "2020-9133.clean201112"
[11] "2022-9163.clean230801"

In [9]:
system("ls /u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2010-002.clean101007", intern = TRUE)

[1] "2010-002.clean101007_X.bed"      "2010-002.clean101007_X.bim"
[3] "2010-002.clean101007_X.fam"      "2010-002.clean101007_X.log"
[5] "2010-002.clean101007_X.nosex"    "2010-002.clean101007_X.sexcheck"
[7] "chrX.dose.vcf.gz"                "chrX.info.gz"

In [16]:
test_input <- read.table("/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2010-002.clean101007/2010-002.clean101007_X.sexcheck")

In [17]:
head(test_input)

  V1        V2        V3     V4     V5      V6
1 FID       IID       PEDSEX SNPSEX STATUS  F
2 AU003305  AU003305  0      1      PROBLEM 1
3 AU020305  AU020305  0      1      PROBLEM 0.9939
4 AU020306  AU020306  0      1      PROBLEM 0.9996
5 AU0226302 AU0226302 0      1      PROBLEM 0.9966
6 AU0226303 AU0226303 0      2      PROBLEM 0.08788

In [18]:
colnames(test_input) <- as.character(unlist(test_input[1, ]))  # Convert the first row to character vector
test_input <- test_input[-1, ]

In [19]:
head(test_input)

  FID       IID       PEDSEX SNPSEX STATUS  F
2 AU003305  AU003305  0      1      PROBLEM 1
3 AU020305  AU020305  0      1      PROBLEM 0.9939
4 AU020306  AU020306  0      1      PROBLEM 0.9996
5 AU0226302 AU0226302 0      1      PROBLEM 0.9966
6 AU0226303 AU0226303 0      2      PROBLEM 0.08788
7 AU025304  AU025304  0      1      PROBLEM 0.9979

In [20]:
test_input <- read.table("/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2010-002.clean101007/2010-002.clean101007_X.sexcheck")
colnames(test_input) <- as.character(unlist(test_input[1, ]))  # Convert the first row to character vector
test_input <- test_input[-1, ]

In [22]:
# Specify the path to the directory
base_path <- "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms"

# Get a list of all subdirectories
dir_list <- list.dirs(base_path, full.names = TRUE, recursive = FALSE)

dir_list

 [1] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2010-002.clean101007"
 [2] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2011-158.clean230815"
 [3] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2013-111A.ATN.clean170906"
 [4] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2013-438.clean230817"
 [5] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2015-9017.clean170906"
 [6] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2016-9174_clean190123"
 [7] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2016-9174-3_clean190123"
 [8] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2017-9154_merge_clean190118"
 [9] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2017-9154-merge_clean181212"
[10] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2020-9133.clean201112"
[11] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2022-9163.clean230801"

In [2]:
sex_files <- c("/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2010-002.clean101007/2010-002.clean101007_X.sexcheck", 
 "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2011-158.clean230815/2011-158.clean230815_X.sexcheck",
 "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2013-111A.ATN.clean170906/2013-111A.ATN.clean170906_X.sexcheck", 
 "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2013-438.clean230817/2013-438.clean230817_X.sexcheck",
 "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2015-9017.clean170906/2015-9017.clean170906_X.sexcheck", 
  "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2016-9174_clean190123/2016-9174_clean190123_X.sexcheck",
 "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2016-9174-3_clean190123/2016-9174-3_clean190123_X.sexcheck",
 "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2017-9154_merge_clean190118/2017-9154_merge_clean190118_X.sexcheck", 
 "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2017-9154-merge_clean181212/2017-9154-merge_clean181212_X.sexcheck", 
 "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2020-9133.clean201112/2020-9133.clean201112_X.sexcheck",
 "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2022-9163.clean230801/2022-9163.clean230801_X.sexcheck")

In [28]:
# Specify the path to the directory
base_path <- "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms"

# Get a list of all subdirectories
dir_list <- list.dirs(base_path, full.names = TRUE, recursive = FALSE)
dir_list

 [1] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2010-002.clean101007"
 [2] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2011-158.clean230815"
 [3] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2013-111A.ATN.clean170906"
 [4] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2013-438.clean230817"
 [5] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2015-9017.clean170906"
 [6] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2016-9174_clean190123"
 [7] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2016-9174-3_clean190123"
 [8] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2017-9154_merge_clean190118"
 [9] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2017-9154-merge_clean181212"
[10] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2020-9133.clean201112"
[11] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2022-9163.clean230801"

In [29]:
file.path(dir_list[1], "*.sexcheck")

[1] "/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2010-002.clean101007/*.sexcheck"

In [32]:

# Initialize an empty list to store data frames
data_list <- list()

sexcheck_files <- sex_files

# Loop through each .sexcheck file found in the current directory
for (file in sexcheck_files) {
    # Read the file
    input <- read.table(file, header = FALSE, fill = TRUE)

    # Set the first row as column names and remove it
    colnames(input) <- as.character(unlist(input[1, ]))
    input <- input[-1, ]  # Remove the first row

    # Add the processed data frame to the list
    data_list[[length(data_list) + 1]] <- input
}

# Combine all data frames into one
combined_data <- do.call(rbind, data_list)

In [3]:
# Initialize an empty list to store data frames
data_list <- list()

sexcheck_files <- sex_files

# Loop through each .sexcheck file
for (file in sexcheck_files) {
    # Read the file
    input <- read.table(file, header = FALSE, fill = TRUE)

    # Set the first row as column names and remove it
    colnames(input) <- as.character(unlist(input[1, ]))
    input <- input[-1, ]  # Remove the first row

    # Extract the portion of the file name between the last "/" and "_X"
    file_name <- sub(".*/(.*)_X.*", "\\1", file)

    # Add a new column for the file name
    input$file <- file_name

    # Add the processed data frame to the list
    data_list[[length(data_list) + 1]] <- input
}

# Combine all data frames into one
combined_data <- do.call(rbind, data_list)

# View the combined data frame
head(combined_data)

  FID       IID       PEDSEX SNPSEX STATUS  F       file
2 AU003305  AU003305  0      1      PROBLEM 1       2010-002.clean101007
3 AU020305  AU020305  0      1      PROBLEM 0.9939  2010-002.clean101007
4 AU020306  AU020306  0      1      PROBLEM 0.9996  2010-002.clean101007
5 AU0226302 AU0226302 0      1      PROBLEM 0.9966  2010-002.clean101007
6 AU0226303 AU0226303 0      2      PROBLEM 0.08788 2010-002.clean101007
7 AU025304  AU025304  0      1      PROBLEM 0.9979  2010-002.clean101007

In [4]:
dim(combined_data)

[1] 2932    7

In [5]:
unique(combined_data$file)

 [1] "2010-002.clean101007"        "2011-158.clean230815"
 [3] "2013-111A.ATN.clean170906"   "2013-438.clean230817"
 [5] "2015-9017.clean170906"       "2016-9174_clean190123"
 [7] "2016-9174-3_clean190123"     "2017-9154_merge_clean190118"
 [9] "2017-9154-merge_clean181212" "2020-9133.clean201112"
[11] "2022-9163.clean230801"

In [33]:
head(combined_data)

  FID       IID       PEDSEX SNPSEX STATUS  F
2 AU003305  AU003305  0      1      PROBLEM 1
3 AU020305  AU020305  0      1      PROBLEM 0.9939
4 AU020306  AU020306  0      1      PROBLEM 0.9996
5 AU0226302 AU0226302 0      1      PROBLEM 0.9966
6 AU0226303 AU0226303 0      2      PROBLEM 0.08788
7 AU025304  AU025304  0      1      PROBLEM 0.9979

In [34]:
length(unique(combined_data$FID))

[1] 2612

In [35]:
dim(combined_data)

[1] 2932    6

In [6]:
write.csv(combined_data, "total_sex_check.csv")

In [48]:
sex_table <- unique(combined_data)

In [38]:
dim(sex_table)

[1] 2912    6

In [49]:
sex_table <- sex_table[,c("IID", "SNPSEX")]

In [50]:
sex_table <- unique(sex_table)

In [51]:
dim(sex_table)

[1] 2613    2

In [52]:
sex_table %>%
  group_by(IID) %>%
  filter(n() > 1)

  IID       SNPSEX
1 AU3101202 2
2 09        1
3 09        0
4 AU3101202 0

In [53]:
combined_data[combined_data$IID == "AU3101202",]

     FID       IID       PEDSEX SNPSEX STATUS  F
409  AU3101202 AU3101202 0      2      PROBLEM -0.03878
2341 AU3101202 AU3101202 0      0      PROBLEM 0.2803

In [54]:
table(combined_data$SNPSEX)

   0    1    2
 146 1835  951