In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.6
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [10]:
ace_snps <- read.table("/u/project/geschwind/shared/GenomicDatasets-processed/ACE_X_chroms/2010-002.clean101007/2010-002.clean101007_snps.snplist")

In [8]:
head(ace_x)

  V1
1 chrX:2781514:C:A
2 chrX:2781604:G:T
3 chrX:2781635:G:A
4 chrX:2781642:G:A
5 chrX:2781777:A:G
6 chrX:2781857:C:CT

In [11]:
ace_snps$V2 <- gsub("^chr", "", gsub("^(chr[^:]+:[^:]+):.*", "\\1", ace_snps$V1))

In [5]:
hm3_snps <- read.table("/u/project/pasaniuc/afcarrol/Projects/20230117_spark_pca_update/hm3_snp_pos.txt")

In [7]:
head(hm3_snps)

  V1
1 1:817341
2 1:818802
3 1:825532
4 1:833068
5 1:843942
6 1:903175

In [14]:
hm3_snps$V2 <- sub(":.*", "", hm3_snps$V1)

In [15]:
unique(hm3_snps$V2)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
[16] "16" "17" "18" "19" "20" "21" "22"

In [17]:
onekg_snps <- read.table("/u/project/pasaniuc/afcarrol/Projects/20230930_1kg_variants/1kg_var.snplist")

In [18]:
onekg_snps$V2 <- sub(":.*", "", onekg_snps$V1)

In [19]:
unique(onekg_snps$V2)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
[16] "16" "17" "18" "19" "20" "21" "22"

In [12]:
ace_sub <- ace_snps[ace_snps$V2 %in% hm3_snps$V1,]

In [13]:
dim(ace_sub <- ace_snps[ace_snps$V2 %in% hm3_snps$V1,])

[1] 0 2